### ISSUE TITLE
Smart-contract `local_hello_name_caller.wat` makes every node crash

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2091]
Steps to reproduce:
- launch network
- `send_smart_contract ek1NWuumgfU2YkkAFkXkAsPFQvrCg5V2Zi15xmYy8434EU96v local_hello_name_caller.wat 100 0.1 1 0` in massa-client

Produces the following errors:
```
2022-01-06T18:18:13.084769Z  INFO regalloc: ================ regalloc.rs: END function ================
2022-01-06T18:18:13.084771Z  INFO regalloc: ================ regalloc.rs: END function ================
2022-01-06T18:18:13.084782Z  INFO regalloc: ================ regalloc.rs: END function ================
thread '<unnamed>' panicked at 'Failed to call __new: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [FrameInfo { module_name: "<module>", func_index: 9, function_name: Some("~lib/rt/tlsf/initialize"), func_start: SourceLoc(1595), instr: SourceLoc(1710) }, FrameInfo { module_name: "<module>", func_index: 12, function_name: Some("~lib/rt/itcms/__new"), func_start: SourceLoc(2455), instr: SourceLoc(2569) }], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
 }', /Users/adrien/.cargo/registry/src/github.com-1ecc6299db9ec823/as-ffi-bindings-0.1.1/src/string_ptr.rs:55:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-01-06T18:18:13.395521Z  INFO massa_protocol_worker::protocol_worker: Connection closed with 8hJhTQtuejM57uCZM5CDTsXsLzVZRiokmDXeRFPxLh9ZVtR1ig
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', massa-execution/src/worker.rs:186:50
2022-01-06T18:18:13.614847Z ERROR massa_node: consensus_event_receiver.wait_event error: failed retrieving consensus controller event
2022-01-06T18:18:13.615342Z  INFO massa_api: API finished cleanly
2022-01-06T18:18:13.615560Z  INFO massa_api: API finished cleanly
2022-01-06T18:18:13.617285Z ERROR massa_consensus::consensus_controller: consensus worker crashed: execution error: Channel error
thread 'main' panicked at 'consensus shutdown failed: ExecutionError(ChannelError("could not send BlockCliqueChanged command to execution"))', massa-node/src/main.rs:247:10
2022-01-06T18:18:13.617644Z  INFO massa_pool::pool_controller: pool worker finished cleanly
2022-01-06T18:18:13.618575Z  INFO massa_protocol_worker::protocol_worker: protocol worker finished cleanly
2022-01-06T18:18:13.621673Z ERROR massa_network::network_controller: network worker crashed: An error occurred during channel communication: could not send on saver_watch_tx
```

[local_hello_name_caller.wat.zip](https://github.com/massalabs/massa/files/7823923/local_hello_name_caller.wat.zip)

**Comment by sebastien-forestier** [comment]
my logs:
```
[2m2022-01-06T18:18:13.037974Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   in: 7 VLRs, 32 RLRs    
[2m2022-01-06T18:18:13.037994Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   main allocation loop: begin    
[2m2022-01-06T18:18:13.038009Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   main allocation loop: end    
[2m2022-01-06T18:18:13.038015Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   create spills_n_reloads for MOVE insns    
[2m2022-01-06T18:18:13.038021Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   create spills_n_reloads for other insns    
[2m2022-01-06T18:18:13.038027Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   create frag_map    
[2m2022-01-06T18:18:13.038034Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   edit_inst_stream    
[2m2022-01-06T18:18:13.038050Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   out: VLRs: 7 initially, 7 processed    
[2m2022-01-06T18:18:13.038056Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   out: VLRs: 0 evicted, 0 spilled    
[2m2022-01-06T18:18:13.038063Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   out: insns: 15 total, 0 spills, 0 reloads, 0 nopzs    
[2m2022-01-06T18:18:13.038069Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   out: spill slots: 0 used    
[2m2022-01-06T18:18:13.038075Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main:   creating RegAllocResult    
[2m2022-01-06T18:18:13.038093Z[0m [32m INFO[0m [2mregalloc::bt_main[0m[2m:[0m alloc_main: end    
[2m2022-01-06T18:18:13.038105Z[0m [32m INFO[0m [2mregalloc[0m[2m:[0m ================ regalloc.rs: END function ================    
thread '<unnamed>' panicked at 'Failed to call __new: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [FrameInfo { module_name: "<module>", func_index: 9, function_name: Some("~lib/rt/tlsf/initialize"), func_start: SourceLoc(1595), instr: SourceLoc(1710) }, FrameInfo { module_name: "<module>", func_index: 12, function_name: Some("~lib/rt/itcms/__new"), func_start: SourceLoc(2455), instr: SourceLoc(2569) }], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
 }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/as-ffi-bindings-0.1.1/src/string_ptr.rs:55:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', massa-execution/src/worker.rs:210:50
[2m2022-01-06T18:18:13.503576Z[0m [32m INFO[0m [2mmassa_consensus::consensus_worker[0m[2m:[0m Staked block gYShPjQGHcBDhxh1HEtaGwVwQz7iLpp9A7oGPj68fhC7GJnyF with address ek1NWuumgfU2YkkAFkXkAsPFQvrCg5V2Zi15xmYy8434EU96v, at cycle 0, period 23, thread 11
[2m2022-01-06T18:18:13.506268Z[0m [32m INFO[0m [2mmassa_consensus::consensus_worker[0m[2m:[0m Next block creation slot for address ek1NWuumgfU2YkkAFkXkAsPFQvrCg5V2Zi15xmYy8434EU96v: cycle 0, period 23, thread 13, at time 2022-01-06 18:18:14.500 UTC
[2m2022-01-06T18:18:13.517252Z[0m [31mERROR[0m [2mmassa_node[0m[2m:[0m consensus_event_receiver.wait_event error: failed retrieving consensus controller event
[2m2022-01-06T18:18:13.517804Z[0m [32m INFO[0m [2mmassa_api[0m[2m:[0m API finished cleanly
[2m2022-01-06T18:18:13.518093Z[0m [31mERROR[0m [2mmassa_consensus::consensus_controller[0m[2m:[0m consensus worker crashed: execution error: Channel error
[2m2022-01-06T18:18:13.518114Z[0m [32m INFO[0m [2mmassa_api[0m[2m:[0m API finished cleanly
thread 'main' panicked at 'consensus shutdown failed: ExecutionError(ChannelError("could not send BlockCliqueChanged command to execution"))', massa-node/src/main.rs:247:10
[2m2022-01-06T18:18:13.518414Z[0m [32m INFO[0m [2mmassa_protocol_worker::protocol_worker[0m[2m:[0m protocol worker finished cleanly
[2m2022-01-06T18:18:13.518499Z[0m [31mERROR[0m [2mmassa_pool::pool_controller[0m[2m:[0m pool worker crashed: Protocol error An error occurred during channel communication: DefaultProtocolController wait_pool_event channel recv failed
```

**Comment by damip** [comment]
Looks like https://github.com/wasmerio/wasmer/issues/1931

**Comment by damip** [comment]
Here are some error logs when running local_hello_name_caller.wat on my computer (it is different from what you got @qdrn ):

* when max_gas is set to 1: [bg_wasm_lowgas.txt](https://github.com/massalabs/massa/files/7827095/bg_wasm_lowgas.txt)
* when max_gas is set to 100000: [bg2_wasm_highgas.txt](https://github.com/massalabs/massa/files/7827107/bg2_wasm_highgas.txt)

**Comment by adrien-zinger** [comment]
The error say that you didn't compile with the flag --exportRuntime. The as-ffi-binding panic with the version 0.1.0 but the 0.2.0 just theow a nice error.

Updating as-ffi-binding in sc-runtime should fix the problem

**Comment by adrien-zinger** [comment]
> The error say that you didn't compile your smart contract with the flag --exportRuntime. The as-ffi-binding panic with the version 0.1.0 but the 0.2.0 just theow a nice error.
> 
> Updating as-ffi-binding in sc-runtime should fix the problem

**Comment by adrien-zinger** [comment]
> The error say that you didn't compile with the flag --exportRuntime. The as-ffi-binding panic with the version 0.1.0 but the 0.2.0 just throw a nice error.
> 
> Updating as-ffi-binding in sc-runtime should fix the problem



`as-ffi-bindings = "0.2.0"`

**Comment by adrien-zinger** [comment]
@qdrn, even if we can fix the panic, you should use the wasm instead of the wat file generated, it's safer. In addition, when you compile your smart contract, use the --exportRuntime flag as in the example in the runtime project (that includes `__new`, `__pin` and `__unpin` in your binary), otherwise you won't be able to interact with other SC.

**Comment by qdrn** [comment]
Ok. Noted.

Tho, we should try using every kind of stuff to test smart contracts. Even stuff that does not make sense at all.

**Comment by damip** [comment]
solved. Thanks to all !
