### ISSUE TITLE
Node crashed after desync instead of bootstrapping again

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2424]
```
2022-03-14T21:17:56.020004Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:17:56.521856Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:17:57.023887Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:17:57.524785Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:17:58.027523Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:17:58.528472Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:17:59.030856Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:17:59.531624Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:18:00.035479Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:18:00.536881Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-14T21:18:01.073825Z ERROR massa_consensus_worker::tools: consensus worker crashed: Proof of stake error: Proof of stake cycle unavailable target cycle incomplete
2022-03-14T21:20:19.077930Z  INFO massa_api: API finished cleanly
2022-03-14T21:20:19.078155Z  INFO massa_api: API finished cleanly
thread 'main' panicked at 'consensus shutdown failed: ProofOfStakeError(PosCycleUnavailable("target cycle incomplete"))', massa-node/src/main.rs:261:10
2022-03-14T21:20:19.087602Z  INFO massa_pool::pool_controller: pool worker finished cleanly
```

**Comment by JeromeSi** [comment]
Hi,
I'va got the same issue with my node
My first WARN :
`2022-03-19T07:20:30.509576Z  INFO massa_consensus_worker::consensus_worker: Next block creation slot for address 2hST5GgbAMAHvUe9JK3MDidt9ppPPMMViTRoN6ZMBYi2mjn34A: cycle 654, period 83804, thread 15, at time 2022-03-19 07:27:51.500 UTC
2022-03-19T07:25:59.206814Z  WARN massa_protocol_worker::protocol_worker: node 87yauV9qfVyn6fq1W7mbSg57Jtaomh1AaZoap7LmAjD1dFcfy1 sent us critically incorrect header, which may be an attack attempt by the remote node or a loss of sync between us and the remote node
2022-03-19T07:27:51.503239Z  INFO massa_consensus_worker::consensus_worker: Staked block wNvaZJq8aU4RsZoAT7zYbqThdrtZVoQiq6LUaBX6CLYEQRFvM with address 2hST5GgbAMAHvUe9JK3MDidt9ppPPMMViTRoN6ZMBYi2mjn34A, at cycle 654, period 83804, thread 15
`
The second WARN : 
`2022-03-19T08:20:45.006888Z  INFO massa_consensus_worker::consensus_worker: Next block creation slot for address 2hST5GgbAMAHvUe9JK3MDidt9ppPPMMViTRoN6ZMBYi2mjn34A: cycle 656, period 84007, thread 31, at time 2022-03-19 08:22:07.500 UTC
2022-03-19T08:21:50.654110Z  WARN massa_network::network_worker: network: could not send NodeSignMessage response upstream
2022-03-19T08:22:07.504904Z  INFO massa_consensus_worker::consensus_worker: Staked block 2iTXmqJBZwg5TZiZRESnk77zxxM5ZVS3Kfdf2bWvHEjvExPoCy with address 2hST5GgbAMAHvUe9JK3MDidt9ppPPMMViTRoN6ZMBYi2mjn34A, at cycle 656, period 84007, thread 31
`
The begining of the end :
`2022-03-19T08:45:36.001373Z  INFO massa_consensus_worker::consensus_worker: Started cycle 657
2022-03-19T08:45:36.001490Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-19T08:45:36.001618Z  WARN massa_node: in response to a desynchronization, the node is going to bootstrap again
2022-03-19T08:45:36.500642Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
`
The end : 
`2022-03-19T08:50:02.365690Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-19T08:50:02.868363Z  WARN massa_consensus_worker::consensus_worker: consensus: could not send GetSelectionDraws response
2022-03-19T08:50:02.868435Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-19T08:50:03.370308Z  WARN massa_consensus_worker::consensus_worker: desynchronization detected because the lookback cycle is not final at the current time
2022-03-19T08:50:03.875274Z  WARN massa_consensus_worker::consensus_worker: consensus: could not send GetAddressesInfo response
2022-03-19T08:50:03.900971Z ERROR massa_consensus_worker::tools: consensus worker crashed: Proof of stake error: Proof of stake cycle unavailable target cycle incomplete
2022-03-19T08:57:38.358145Z  INFO massa_api: API finished cleanly
2022-03-19T08:57:38.358592Z  INFO massa_api: API finished cleanly
thread 'main' panicked at 'consensus shutdown failed: ProofOfStakeError(PosCycleUnavailable("target cycle incomplete"))', massa-node/src/main.rs:261:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`
Massa is in a docker : 
`root@53166755c6c2:/Massa# rustc --version
rustc 1.61.0-nightly (9fcbc3205 2022-03-04)
root@53166755c6c2:/Massa# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
`
I restart the node without update without compilation and work fine 24h at this moment.
