### ISSUE TITLE
Error in a little network

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2452]
I have run a little network with 3 nodes and tried to load it with some operations and got this error log : 
[logs.txt](https://github.com/massalabs/massa/files/8325122/logs.txt)

Don't know if it's normal or not and why.

**Comment by damip** [comment]
not normal, and critical !

**Comment by damip** [comment]
```
thread 'main' panicked at 'consensus shutdown failed: GraphError(ContainerInconsistency("inconsistency inside block statuses iterating through descendants of 2aAetkKmGfArVoZP4aM75xkW22Qm6QU5fnXMbqXjA9vozBemGa - missing hM8fuDLsRGhmdo38AmgUX1XqMMvxNs499ztzd8hgE2xHcSNxx"))', massa-node/src/main.rs:275:10
stack backtrace:
   0:     0x5572fdd9ee9d - std::backtrace_rs::backtrace::libunwind::trace::h131f58146b42c005
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5572fdd9ee9d - std::backtrace_rs::backtrace::trace_unsynchronized::hc1d3ac4d4b926cc5
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5572fdd9ee9d - std::sys_common::backtrace::_print_fmt::h2e1e750d171be220
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5572fdd9ee9d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h653601d01d36e8e0
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5572fddc319c - core::fmt::write::h282e005fb170faeb
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/core/src/fmt/mod.rs:1190:17
   5:     0x5572fdd98e41 - std::io::Write::write_fmt::h66472f7e7dc9a2c4
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/io/mod.rs:1655:15
   6:     0x5572fdda09c5 - std::sys_common::backtrace::_print::h6c2e050787dc1dbb
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5572fdda09c5 - std::sys_common::backtrace::print::hcce35e53ca1b7643
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5572fdda09c5 - std::panicking::default_hook::{{closure}}::h37abdb1a8201ceb5
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:295:22
   9:     0x5572fdda0679 - std::panicking::default_hook::h595b8146b2c11047
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:314:9
  10:     0x5572fdda0f12 - std::panicking::rust_panic_with_hook::h3bd91c36fee449e0
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:698:17
  11:     0x5572fdda0df7 - std::panicking::begin_panic_handler::{{closure}}::h5531bb949fbb3fe6
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:588:13
  12:     0x5572fdd9f354 - std::sys_common::backtrace::__rust_end_short_backtrace::hee4b90f4025310e8
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5572fdda0b29 - rust_begin_unwind
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:584:5
  14:     0x5572fd4281a3 - core::panicking::panic_fmt::h1cc15fe9d13cf937
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/core/src/panicking.rs:143:14
  15:     0x5572fd428293 - core::result::unwrap_failed::h74641d498243a821
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/core/src/result.rs:1784:5
  16:     0x5572fd5c9a93 - massa_node::stop::{{closure}}::h27bd5683c804dbe9
  17:     0x5572fd5a3822 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h47f07ad4c1ab32f1
  18:     0x5572fd5ced1d - std::thread::local::LocalKey<T>::with::h168dbe62c04b5e60
  19:     0x5572fd46bd3f - tokio::park::thread::CachedParkThread::block_on::h668c76bb73a4a493
  20:     0x5572fd45b43d - tokio::runtime::thread_pool::ThreadPool::block_on::hbd47dc9277e5c9cf
  21:     0x5572fd4bb1fc - tokio::runtime::Runtime::block_on::hb5dccd079af592e6
  22:     0x5572fd4e0bf6 - massa_node::main::h89e95766fac67bd7
  23:     0x5572fd461b23 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1c6615eebf5333a1
  24:     0x5572fd497fa9 - std::rt::lang_start::{{closure}}::hfabaff0b297837d8
  25:     0x5572fdd92f8b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc24eb259fc515063
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/core/src/ops/function.rs:259:13
  26:     0x5572fdd92f8b - std::panicking::try::do_call::h77c7c427c4b17bcb
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:492:40
  27:     0x5572fdd92f8b - std::panicking::try::h417d8f46b14e8c67
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:456:19
  28:     0x5572fdd92f8b - std::panic::catch_unwind::h0c4c584b8d3dfaa3
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panic.rs:137:14
  29:     0x5572fdd92f8b - std::rt::lang_start_internal::{{closure}}::hbcbfcaf5dc11f640
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/rt.rs:128:48
  30:     0x5572fdd92f8b - std::panicking::try::do_call::h2bcbc2a037ddcdbe
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:492:40
  31:     0x5572fdd92f8b - std::panicking::try::h912c71ff3efb554f
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panicking.rs:456:19
  32:     0x5572fdd92f8b - std::panic::catch_unwind::hc5fab086ea97b412
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/panic.rs:137:14
  33:     0x5572fdd92f8b - std::rt::lang_start_internal::h0b4bd55be5830536
                               at /rustc/c84f39e6c08397d4ab9b51b472002a8bfc3b5b59/library/std/src/rt.rs:128:20
  34:     0x5572fd4e0ce2 - main
  35:     0x7f30f873309b - __libc_start_main
  36:     0x5572fd42849a - _start
  37:                0x0 - <unknown>
```

**Comment by damip** [comment]
The error is triggered because `block_graph::get_active_block_and_descendants` looks for the descendants of a block (2aAetkKmGfArVoZP4aM75xkW22Qm6QU5fnXMbqXjA9vozBemGa, which is found) but does not find one of its descendants (hM8fuDLsRGhmdo38AmgUX1XqMMvxNs499ztzd8hgE2xHcSNxx) as active in the graph.

This should never happen.

get_active_block_and_descendants is called only during the TI and GPI tests inside block_graph::check_header. 

Note that the looked up block (2aAetkKmGfArVoZP4aM75xkW22Qm6QU5fnXMbqXjA9vozBemGa) is found as active.

Possible causes, at the moment of the TI/GPI tests:
* a descendant was added to the descendant list of a block, but not to the graph
* a descendant was removed from the graph but not from its ancestor's descendants
* descendant computation failed after bootstrap

**Comment by damip** [comment]
Problem found: children were deleted from the wrong thread
