### ISSUE TITLE
Shared storage bug : Missing block crash at bootstrap

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#2472]
Network spec : 1 bootstrap node, 1 node connecting 50 seconds after genesis timestamp.

Log of the node that connect who crash : 
```
2022-03-29T16:35:10.080638Z  INFO massa_node: Node version : SAND.0.0
2022-03-29T16:35:10.080685Z  INFO massa_bootstrap: Start bootstrapping from 169.202.0.2:31245
2022-03-29T16:35:10.080856Z  INFO massa_bootstrap::client_binder: in handshake
2022-03-29T16:35:10.080902Z  INFO massa_bootstrap::client_binder: sended handshake
2022-03-29T16:35:10.082185Z  INFO massa_bootstrap::client_binder: readed handshake
2022-03-29T16:35:10.088226Z  INFO massa_bootstrap::client_binder: veirfied handshake
2022-03-29T16:35:11.217730Z  INFO massa_bootstrap: Successful bootstrap
2022-03-29T16:35:11.217983Z DEBUG massa_network_worker: starting network controller
2022-03-29T16:35:11.218370Z  INFO massa_network_worker: The node_id of this node is: 5htMt1hq7QWfnNuKTtWYNiXzxnCtGLvVSCwTkYCzjXBMnMApa9
2022-03-29T16:35:11.218435Z DEBUG massa_network_worker: Loading peer database
2022-03-29T16:35:11.218651Z DEBUG massa_network_worker: network controller started
2022-03-29T16:35:11.218664Z DEBUG massa_protocol_worker::protocol_worker: starting protocol controller
2022-03-29T16:35:11.218719Z DEBUG massa_protocol_worker::protocol_worker: protocol controller ready
2022-03-29T16:35:11.218741Z DEBUG massa_pool::pool_controller: starting pool controller
2022-03-29T16:35:11.218924Z DEBUG massa_consensus_worker::tools: starting consensus controller
2022-03-29T16:35:11.248200Z  INFO massa_consensus_worker::consensus_worker: Started node at time 2022-03-29T16:35:11Z, cycle 0, period 3, thread 10
2022-03-29T16:35:11.248216Z DEBUG massa_bootstrap: starting bootstrap server
2022-03-29T16:35:11.248222Z  INFO massa_consensus_worker::consensus_worker: Staking enabled for address: JBbufTa6AywQDeCWvm6oSeik5DhwRLN87uFYuCXx4i1o5isL3
thread '<unnamed>' panicked at 'Missing block in storage.', massa-execution-worker/src/worker.rs:330:18
stack backtrace:
   0:     0x555d41fc740d - std::backtrace_rs::backtrace::libunwind::trace::hb8664f5c920dcd17
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x555d41fc740d - std::backtrace_rs::backtrace::trace_unsynchronized::h4718639a025d9e7f
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555d41fc740d - std::sys_common::backtrace::_print_fmt::h147f7c369d4f1e8e
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x555d41fc740d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee801905e555ec30
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x555d41feb70c - core::fmt::write::h4bb35aa347c570f4
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/fmt/mod.rs:1190:17
   5:     0x555d41fc1311 - std::io::Write::write_fmt::h6ed268cd0958975b
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/io/mod.rs:1655:15
   6:     0x555d41fc8f35 - std::sys_common::backtrace::_print::h3f974cf4bd76b112
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x555d41fc8f35 - std::sys_common::backtrace::print::h56cc71e242d02ce1
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x555d41fc8f35 - std::panicking::default_hook::{{closure}}::hca67c27c011873e3
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:295:22
   9:     0x555d41fc8be9 - std::panicking::default_hook::ha53803c35aaf5526
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:314:9
  10:     0x555d41fc9482 - std::panicking::rust_panic_with_hook::hc072423965447af2
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:698:17
  11:     0x555d41fc9367 - std::panicking::begin_panic_handler::{{closure}}::hc90fd7eef8f5bc28
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:588:13
  12:     0x555d41fc78c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h817639bb6106d966
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x555d41fc9099 - rust_begin_unwind
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:584:5
  14:     0x555d4163c3f3 - core::panicking::panic_fmt::h97422e022191d341
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:143:14
  15:     0x555d41fe8d71 - core::panicking::panic_display::h798b071807c97cbe
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:72:5
  16:     0x555d41fe8d1b - core::panicking::panic_str::he9fbda5b588907d6
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:56:5
  17:     0x555d4163c266 - core::option::expect_failed::h6bf88497119f68f7
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/option.rs:1874:5
  18:     0x555d4185ebd3 - massa_execution_worker::worker::ExecutionThread::main_loop::ha9c9c8b606c0dda5
  19:     0x555d41862b8e - std::sys_common::backtrace::__rust_begin_short_backtrace::hac46e35c92879068
  20:     0x555d418632bd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4c3ea0a008bbe5b6
  21:     0x555d41fccfe3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf0cca23978c89840
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/alloc/src/boxed.rs:1861:9
  22:     0x555d41fccfe3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9da765b1ac504456
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/alloc/src/boxed.rs:1861:9
  23:     0x555d41fccfe3 - std::sys::unix::thread::Thread::new::thread_start::hb3629e14c6b629e3
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys/unix/thread.rs:108:17
  24:     0x7fc9bdd50fa3 - start_thread
  25:     0x7fc9bdaf94cf - clone
  26:                0x0 - <unknown>
```

**Comment by gterzian** [comment]
I think the problem was that we were not storing the block in shared storage when boostrapping. Addressed in https://github.com/massalabs/massa/pull/2428/commits/edea1d6be064b17141a90cd76be5d92032cd8b78

**Comment by AurelienFT** [comment]
An other logs that appears after the modifications : 
```
setting up node...
2022-03-30T09:37:19.043291Z  INFO massa_node: Node version : SAND.0.0
2022-03-30T09:37:19.043327Z  INFO massa_bootstrap: Start bootstrapping from 169.202.0.2:31245
2022-03-30T09:37:19.046463Z  INFO massa_bootstrap::client_binder: in handshake
2022-03-30T09:37:19.046497Z  INFO massa_bootstrap::client_binder: sended handshake
2022-03-30T09:37:19.050131Z  INFO massa_bootstrap::client_binder: readed handshake
2022-03-30T09:37:19.056918Z  INFO massa_bootstrap::client_binder: veirfied handshake
2022-03-30T09:37:21.401514Z  INFO massa_bootstrap: Successful bootstrap
2022-03-30T09:37:21.401655Z DEBUG massa_network_worker: starting network controller
2022-03-30T09:37:21.402132Z  INFO massa_network_worker: The node_id of this node is: 5htMt1hq7QWfnNuKTtWYNiXzxnCtGLvVSCwTkYCzjXBMnMApa9
2022-03-30T09:37:21.402195Z DEBUG massa_network_worker: Loading peer database
2022-03-30T09:37:21.402413Z DEBUG massa_network_worker: network controller started
2022-03-30T09:37:21.402423Z DEBUG massa_protocol_worker::protocol_worker: starting protocol controller
2022-03-30T09:37:21.402446Z DEBUG massa_protocol_worker::protocol_worker: protocol controller ready
2022-03-30T09:37:21.402523Z DEBUG massa_pool::pool_controller: starting pool controller
2022-03-30T09:37:21.402766Z DEBUG massa_consensus_worker::tools: starting consensus controller
2022-03-30T09:37:21.422897Z DEBUG massa_network_worker::network_worker: starting outgoing connection attempt towards ip=169.202.0.2
2022-03-30T09:37:21.424301Z DEBUG massa_network_worker::network_worker: out connection towards ip=169.202.0.2 established => connection_id=0
2022-03-30T09:37:21.424321Z DEBUG massa_network_worker::handshake_worker: starting handshake with connection_id=0
2022-03-30T09:37:21.429436Z  INFO massa_consensus_worker::consensus_worker: Started node at time 2022-03-30T09:37:21Z, cycle 0, period 4, thread 12
2022-03-30T09:37:21.429454Z DEBUG massa_bootstrap: starting bootstrap server
2022-03-30T09:37:21.429485Z  INFO massa_consensus_worker::consensus_worker: Staking enabled for address: JBbufTa6AywQDeCWvm6oSeik5DhwRLN87uFYuCXx4i1o5isL3
thread '<unnamed>' panicked at 'Missing block in storage.', massa-execution-worker/src/worker.rs:330:18
stack backtrace:
2022-03-30T09:37:21.438569Z DEBUG massa_network_worker::network_worker: handshake with connection_id=0 succeeded => node_id=5tuXKh377eV5DNp8xzLo5dhJJVZoAmRuP9CGnKAhGp3xFrhuMv
2022-03-30T09:37:21.438638Z  INFO massa_protocol_worker::protocol_worker: Connected to node 5tuXKh377eV5DNp8xzLo5dhJJVZoAmRuP9CGnKAhGp3xFrhuMv
2022-03-30T09:37:21.439681Z DEBUG massa_network_worker::node_worker: timer-based asking node_id=5tuXKh377eV5DNp8xzLo5dhJJVZoAmRuP9CGnKAhGp3xFrhuMv for peer list
   0:     0x5631f27eb40d - std::backtrace_rs::backtrace::libunwind::trace::hb8664f5c920dcd17
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5631f27eb40d - std::backtrace_rs::backtrace::trace_unsynchronized::h4718639a025d9e7f
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5631f27eb40d - std::sys_common::backtrace::_print_fmt::h147f7c369d4f1e8e
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5631f27eb40d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee801905e555ec30
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5631f280f70c - core::fmt::write::h4bb35aa347c570f4
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/fmt/mod.rs:1190:17
   5:     0x5631f27e5311 - std::io::Write::write_fmt::h6ed268cd0958975b
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/io/mod.rs:1655:15
   6:     0x5631f27ecf35 - std::sys_common::backtrace::_print::h3f974cf4bd76b112
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5631f27ecf35 - std::sys_common::backtrace::print::h56cc71e242d02ce1
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5631f27ecf35 - std::panicking::default_hook::{{closure}}::hca67c27c011873e3
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:295:22
   9:     0x5631f27ecbe9 - std::panicking::default_hook::ha53803c35aaf5526
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:314:9
  10:     0x5631f27ed482 - std::panicking::rust_panic_with_hook::hc072423965447af2
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:698:17
  11:     0x5631f27ed367 - std::panicking::begin_panic_handler::{{closure}}::hc90fd7eef8f5bc28
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:588:13
  12:     0x5631f27eb8c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h817639bb6106d966
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5631f27ed099 - rust_begin_unwind
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:584:5
  14:     0x5631f1e603f3 - core::panicking::panic_fmt::h97422e022191d341
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:143:14
  15:     0x5631f280cd71 - core::panicking::panic_display::h798b071807c97cbe
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:72:5
  16:     0x5631f280cd1b - core::panicking::panic_str::he9fbda5b588907d6
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:56:5
  17:     0x5631f1e60266 - core::option::expect_failed::h6bf88497119f68f7
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/option.rs:1874:5
  18:     0x5631f2082bd3 - massa_execution_worker::worker::ExecutionThread::main_loop::ha9c9c8b606c0dda5
  19:     0x5631f2086b8e - std::sys_common::backtrace::__rust_begin_short_backtrace::hac46e35c92879068
  20:     0x5631f20872bd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4c3ea0a008bbe5b6
  21:     0x5631f27f0fe3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf0cca23978c89840
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/alloc/src/boxed.rs:1861:9
  22:     0x5631f27f0fe3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9da765b1ac504456
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/alloc/src/boxed.rs:1861:9
  23:     0x5631f27f0fe3 - std::sys::unix::thread::Thread::new::thread_start::hb3629e14c6b629e3
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys/unix/thread.rs:108:17
  24:     0x7f60a5992fa3 - start_thread
  25:     0x7f60a573b4cf - clone
  26:                0x0 - <unknown>
2022-03-30T09:37:21.443646Z DEBUG massa_network_worker::network_event::event_impl: node_id=5tuXKh377eV5DNp8xzLo5dhJJVZoAmRuP9CGnKAhGp3xFrhuMv asked us for peer list
2022-03-30T09:37:21.443670Z DEBUG massa_network_worker::network_event::event_impl: node_id=5tuXKh377eV5DNp8xzLo5dhJJVZoAmRuP9CGnKAhGp3xFrhuMv sent us a peer list (2 ips)
2022-03-30T09:37:21.797790Z ERROR massa_node: consensus_event_receiver.wait_event error: failed retrieving consensus controller event
2022-03-30T09:37:21.798052Z  INFO massa_api: API finished cleanly
2022-03-30T09:37:21.798145Z  INFO massa_api: API finished cleanly
2022-03-30T09:37:21.800677Z ERROR massa_consensus_worker::tools: consensus worker crashed: Graph error: missing block
thread 'main' panicked at 'consensus shutdown failed: GraphError(MissingBlock)', massa-node/src/main.rs:291:10
stack backtrace:
   0:     0x5631f27eb40d - std::backtrace_rs::backtrace::libunwind::trace::hb8664f5c920dcd17
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5631f27eb40d - std::backtrace_rs::backtrace::trace_unsynchronized::h4718639a025d9e7f
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5631f27eb40d - std::sys_common::backtrace::_print_fmt::h147f7c369d4f1e8e
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5631f27eb40d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee801905e555ec30
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5631f280f70c - core::fmt::write::h4bb35aa347c570f4
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/fmt/mod.rs:1190:17
   5:     0x5631f27e5311 - std::io::Write::write_fmt::h6ed268cd0958975b
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/io/mod.rs:1655:15
   6:     0x5631f27ecf35 - std::sys_common::backtrace::_print::h3f974cf4bd76b112
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5631f27ecf35 - std::sys_common::backtrace::print::h56cc71e242d02ce1
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5631f27ecf35 - std::panicking::default_hook::{{closure}}::hca67c27c011873e3
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:295:22
   9:     0x5631f27ecbe9 - std::panicking::default_hook::ha53803c35aaf5526
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:314:9
  10:     0x5631f27ed482 - std::panicking::rust_panic_with_hook::hc072423965447af2
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:698:17
  11:     0x5631f27ed367 - std::panicking::begin_panic_handler::{{closure}}::hc90fd7eef8f5bc28
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:588:13
  12:     0x5631f27eb8c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h817639bb6106d966
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5631f27ed099 - rust_begin_unwind
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:584:5
  14:     0x5631f1e603f3 - core::panicking::panic_fmt::h97422e022191d341
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/panicking.rs:143:14
  15:     0x5631f1e604e3 - core::result::unwrap_failed::h4aef46fe07c82bfe
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/result.rs:1785:5
  16:     0x5631f1fe4f5b - massa_node::stop::{{closure}}::hc1960298e3caf3dd
  17:     0x5631f1fc5df8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h967819fa41aa3dc5
  18:     0x5631f1ff310d - std::thread::local::LocalKey<T>::with::h8345063b18e042fb
  19:     0x5631f1ead05f - tokio::park::thread::CachedParkThread::block_on::h0e75ce6f6e011ca7
  20:     0x5631f1e993dd - tokio::runtime::thread_pool::ThreadPool::block_on::h9db0da986c71a43f
  21:     0x5631f1e89b0c - tokio::runtime::Runtime::block_on::h72d2ab94e22abf62
  22:     0x5631f1fe78d6 - massa_node::main::hdb35d2a54d35c214
  23:     0x5631f1ea3d03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h843418bc9696cfb2
  24:     0x5631f1ed6e19 - std::rt::lang_start::{{closure}}::hab7dae1ac39b1d73
  25:     0x5631f27df4fb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7d0036e321e01b36
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/core/src/ops/function.rs:259:13
  26:     0x5631f27df4fb - std::panicking::try::do_call::hcfeb9fccc4bee9d6
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:492:40
  27:     0x5631f27df4fb - std::panicking::try::h38027b20228ce951
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:456:19
  28:     0x5631f27df4fb - std::panic::catch_unwind::hd9a36c61eae1832a
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panic.rs:137:14
  29:     0x5631f27df4fb - std::rt::lang_start_internal::{{closure}}::h80b48e1116e870ed
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/rt.rs:128:48
  30:     0x5631f27df4fb - std::panicking::try::do_call::h6684ff5441775394
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:492:40
  31:     0x5631f27df4fb - std::panicking::try::h86017a0fc1e7f6a4
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panicking.rs:456:19
  32:     0x5631f27df4fb - std::panic::catch_unwind::hd5f5564907b6382f
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/panic.rs:137:14
  33:     0x5631f27df4fb - std::rt::lang_start_internal::h51bfcb7dda8c7945
                               at /rustc/1d9c262eea411ec5230f8a4c9ba50b3647064da4/library/std/src/rt.rs:128:20
  34:     0x5631f1fe79c2 - main
  35:     0x7f60a566609b - __libc_start_main
  36:     0x5631f1e606ee - _start
  37:                0x0 - <unknown>
2022-03-30T09:37:21.802467Z ERROR massa_pool::pool_controller: pool worker crashed: Protocol error An error occurred during channel communication: DefaultProtocolController wait_pool_event channel recv failed
2022-03-30T09:37:21.802489Z  INFO massa_protocol_worker::protocol_worker: protocol worker finished cleanly
```

**Comment by AurelienFT** [comment]
Just tested it. Fixed. Thank you ! 🎉
