### ISSUE TITLE
Crash and routable issues

### ISSUE THREAD

**Issue by moonshot211** [massalabs/massa#2618]
Last episode everything worked perfectly. I have changed nothing since on my VPS. But now for two days, I noticed that everytime I am selected to created a block my node crash and thus I miss every block. I restart by buying rolls, waits for my rolls to be active and then I crash when I am selected.

Concerning the routability issue, I noticed I am not longer routable whereas my port 31244 & 31245 are opened, I have connection In and similar ID/IP. Last episode, I had roughly 60% routable tests passed and today only 1 out of 85 whereas nothing changed on my side.

I restarted my node and my computer several times without success.

- OS: Ubuntu VPS
- Version: 20

The log file was too big therefore I uploaded it on Google Drive:
https://drive.google.com/file/d/1R5ccYeuTQpzXvbyHIEyRw_AGs4JL7mpO/view?usp=sharing

I am waiting for your help, 

Thank you for your work.

**Comment by moonshot211** [comment]
An other example, if it could help. Logs 2.

Google Drive link:
https://drive.google.com/file/d/11h5Y6Y--RxswQeMf3lLXgwwJoNZUSkLl/view?usp=sharing

**Comment by Punkoivan** [comment]
There are at least 2 issues like yours:

https://github.com/massalabs/massa/issues/2522
https://github.com/massalabs/massa/issues/2525

without an answer.

Looks like I have the same case as you do.

**Comment by AurelienFT** [comment]
I found something interesting in the logs @damip : 
```
consensus worker crashed: Graph error: missing block missing block in processing incoming block: ktovuKuSMf9tT3ejEAU5TUbyyLtWt6nm8GATZj7hZe39oBy4h
thread 'main' panicked at 'consensus shutdown failed: GraphError(MissingBlock("missing block in processing incoming block: ktovuKuSMf9tT3ejEAU5TUbyyLtWt6nm8GATZj7hZe39oBy4h"))', massa-node/src/main.rs:292:10
stack backtrace:
   0:     0x5607f0901bbd - std::backtrace_rs::backtrace::libunwind::trace::h85cc47332f2b05a9
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5607f0901bbd - std::backtrace_rs::backtrace::trace_unsynchronized::h822c2fc2b1a1a752
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5607f0901bbd - std::sys_common::backtrace::_print_fmt::h678c9b8abf6c5083
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5607f0901bbd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2fb21895faf729c2
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5607f092676c - core::fmt::write::h6dc4a63f2d3360d8
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/core/src/fmt/mod.rs:1196:17
   5:     0x5607f08fbc41 - std::io::Write::write_fmt::h8fe2d520dd3fbf2e
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/io/mod.rs:1654:15
   6:     0x5607f09033d5 - std::sys_common::backtrace::_print::h6c3478d5fa62e7d8
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5607f09033d5 - std::sys_common::backtrace::print::hd6d4473e0c0113a9
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5607f09033d5 - std::panicking::default_hook::{{closure}}::h4dec78d051eecf7c
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:295:22
   9:     0x5607f0903049 - std::panicking::default_hook::hc13b58dcc91e88ba
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:314:9
  10:     0x5607f09039a8 - std::panicking::rust_panic_with_hook::h3dd403ae323eac6a
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:698:17
  11:     0x5607f0903857 - std::panicking::begin_panic_handler::{{closure}}::h626a139ef0a3dc34
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:588:13
  12:     0x5607f0902074 - std::sys_common::backtrace::__rust_end_short_backtrace::h583c150e9a9018e5
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5607f0903589 - rust_begin_unwind
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:584:5
  14:     0x5607f0016fc3 - core::panicking::panic_fmt::hfe41b8371c78aa80
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/core/src/panicking.rs:142:14
  15:     0x5607f00170b3 - core::result::unwrap_failed::h336331a458e5cc33
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/core/src/result.rs:1785:5
  16:     0x5607f019fa6b - massa_node::stop::{{closure}}::h1d986506daf55d66
  17:     0x5607f017b208 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h891bb1b0878a73c6
  18:     0x5607f01a2fed - std::thread::local::LocalKey<T>::with::h670cd14d47ae23df
  19:     0x5607f00691df - tokio::park::thread::CachedParkThread::block_on::h87d3e22d450b5103
  20:     0x5607f006947d - tokio::runtime::thread_pool::ThreadPool::block_on::h404fea18be12d39d
  21:     0x5607f004208c - tokio::runtime::Runtime::block_on::h3cf2eb1e60a994cc
  22:     0x5607f01a2406 - massa_node::main::h58cdffe823f4ffd9
  23:     0x5607f005ec23 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd5ac7d6f9e3c7e4a
  24:     0x5607f008b3e9 - std::rt::lang_start::{{closure}}::hddd508ace299a05d
  25:     0x5607f08f5e2e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd85a4410fe6bba5e
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/core/src/ops/function.rs:280:13
  26:     0x5607f08f5e2e - std::panicking::try::do_call::h4a431038dcafef46
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:492:40
  27:     0x5607f08f5e2e - std::panicking::try::h04bc17e1ee3a51d6
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:456:19
  28:     0x5607f08f5e2e - std::panic::catch_unwind::haf5dd4d90cb5958b
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panic.rs:137:14
  29:     0x5607f08f5e2e - std::rt::lang_start_internal::{{closure}}::h210b944105131feb
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/rt.rs:128:48
  30:     0x5607f08f5e2e - std::panicking::try::do_call::hed277b90ebad4aba
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:492:40
  31:     0x5607f08f5e2e - std::panicking::try::h7e777b2dba6feb72
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panicking.rs:456:19
  32:     0x5607f08f5e2e - std::panic::catch_unwind::h02df771442815132
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/panic.rs:137:14
  33:     0x5607f08f5e2e - std::rt::lang_start_internal::h6b1f53b2f35ed05f
                               at /rustc/ecd44958e0a21110d09862ee080d95a4ca6c52f8/library/std/src/rt.rs:128:20
  34:     0x5607f01a24f2 - main
  35:     0x7ff58472e0b3 - __libc_start_main
  36:     0x5607f00172be - _start
  37:                0x0 - <unknown>
2022-05-13T21:56:07.222681Z  WARN massa_network_worker::node_worker: writer exited unexpectedly for node 7cRrvZcZ6XTco2ttvqud2cCmD93sf5xBEYbuLa3neHdypSV4iE
2022-05-13T21:56:07.243260Z  WARN massa_network_worker::peer_info_database: could not dump peers to file: IO error : background task failed
2022-05-13T21:56:07.246491Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246598Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246644Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246688Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246731Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246768Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246804Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246839Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246878Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.246931Z  WARN massa_network_worker::network_worker: a node worker panicked: cancelled
2022-05-13T21:56:07.247033Z  INFO massa_network_worker: network worker finished cleanly
```

**Comment by Punkoivan** [comment]
More logs, I hope it could be handy:
```
2022-05-16T21:15:19.108872Z ERROR massa_consensus_worker::tools: consensus worker crashed: Send  channel error : could not send get endorsement by address response: {}                                                       
thread 'main' panicked at 'consensus shutdown failed: SendChannelError("could not send get endorsement by address response: {}")', massa-node/src/main.rs:292:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/core/src/result.rs:1035:23
   4: massa_node::stop::{{closure}}
             at ./src/main.rs:289:35
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/core/src/future/mod.rs:91:19
   6: massa_node::main::{{closure}}
             at ./src/main.rs:406:10
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/core/src/future/mod.rs:91:19
   8: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
   9: tokio::coop::with_budget::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/std/src/thread/local.rs:445:16
  11: std::thread::local::LocalKey<T>::with
             at /rustc/f1f721e64014863f41c1a386b04af04c2de25321/library/std/src/thread/local.rs:421:9
```

**Comment by AurelienFT** [comment]
For the first error #2624 has been created.

**Comment by Punkoivan** [comment]
Looks like with TEST11 it has been fixed.
Thank you guys.

**Comment by damip** [comment]
Yes it should be ok now :) closing
