### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by wirr-cmd** [massalabs/massa#3139]
Le node s'arrête de temps en temps sur la version 15.
Comme demandé sur le discord voici les dernières lignes du fichier log.

```
[2m2022-10-09T19:15:45.566809Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
thread '<unnamed>' panicked at '[2m2022-10-09T19:15:45.568053Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
couldn't get the expected block producer for a missed slot: CycleUnavailable(178)', massa-execution-worker/src/execution.rs:889:18
stack backtrace:
[2m2022-10-09T19:15:46.000524Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 22784, thread: 20): `CycleUnavailable`: PoS cycle 178 is needed but is absent from cache
[2m2022-10-09T19:15:46.000548Z[0m [33m WARN[0m [2mmassa_factory_worker::block_factory[0m[2m:[0m block factory could not get selector draws for slot (period: 22784, thread: 4): `CycleUnavailable`: PoS cycle 178 is needed but is absent from cache
[2m2022-10-09T19:15:46.045360Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
[2m2022-10-09T19:15:46.046382Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
[2m2022-10-09T19:15:46.047500Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
   0:     0x558149747ee0 - std::backtrace_rs::backtrace::libunwind::trace::h0940e595a024cae9
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x558149747ee0 - std::backtrace_rs::backtrace::trace_unsynchronized::h105f21b55a45a169
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558149747ee0 - std::sys_common::backtrace::_print_fmt::h3a2ed111c2bd9337
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x558149747ee0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9029dd42bc5e75b6
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:45:22
[2m2022-10-09T19:15:46.048540Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
[2m2022-10-09T19:15:46.050100Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
   4:     0x55814976c66e - core::fmt::write::he3e1f91c10d6c224
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/core/src/fmt/mod.rs:1209:17
   5:     0x558149741e25 - std::io::Write::write_fmt::he1f986100980651d
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/io/mod.rs:1679:15
[2m2022-10-09T19:15:46.050489Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
   6:     0x558149749a73 - std::sys_common::backtrace::_print::h26c5f0fe9d048f5c
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x558149749a73 - std::sys_common::backtrace::print::h9d099d945c0c1b8a
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x558149749a73 - std::panicking::default_hook::{{closure}}::h56372a8ac9698e26
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:267:22
   9:     0x55814974974a - std::panicking::default_hook::h73cceb7588e9295f
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:286:9
  10:     0x558148a5768e - massa_node[2m2022-10-09T19:15:46.051905Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
::main::{{closure}}::{{closure}}::h2b82fe726bab0a2e
  11:     0x55814974a1bb - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0f73c471a795acd8
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1952:9
  12:     0x55814974a1bb - std::panicking::rust_panic_with_hook::hf37833f4792b3823
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:673:13
  13:     0x55814974a017 - std::panicking::begin_panic_handler::{{closure}}::hc7fd5d2a7e5e3a2c
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:560:13
  14:     0x55814974838c - std::sys_common::backtrace[2m2022-10-09T19:15:46.500686Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 22784, thread: 21): `CycleUnavailable`: PoS cycle 178 is needed but is absent from cache
::__rust_end_short_backtrace::hff4139a3352a2109
       [2m2022-10-09T19:15:46.500713Z[0m [33m WARN[0m [2mmassa_factory_worker::block_factory[0m[2m:[0m block factory could not get selector draws for slot (period: 22784, thread: 5): `CycleUnavailable`: PoS cycle 178 is needed but is absent from cache
                        at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x558149749d32 - rust_begin_unwind
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:556:5
  16:     0x5581488e3a53 - core::panicking::panic_fmt::ha0d07fe43fc911c7
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/core/src/panicking.rs:142:14
  17:     0x5581488e3ba3 - core::result::unwrap_failed::h38e5bbe9e4d8a288
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/core/src/result.rs:1791:5
  18:     0x5581490d4dfe - massa_execution_worker::execution::ExecutionState::execute_slot::hd6f94042c71eb23c
  19:     0x5581490d653b - massa_execution_worker::execution::ExecutionState::execute_candidate_slot::h82999a94cbacf676
  20:     0x5581490b3477 - massa_execution_worker::worker::ExecutionThread::main_loop::{{closure}}::h224ce1f4e245a3e9
  21:     0x5581490b3077 - massa_execution_worker::slot_sequencer::SlotSequencer::run_task_with::hcfff3a2abe4d5459
  22:     0x558149099a4c - massa_execution_worker::worker::ExecutionThread::main_loop::h9edf69f14a7b6468
  23:     0x5581490e43ba - std::sys_common::backtrace::__rust_begin_short_backtrace::he82ece5350c6b35c
  24:     0x5581490a146c - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb804630fefedba7
  25:     0x55814974d483 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc84bda482f2a673d
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1938:9
  26:     0x55814974d483 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc8d281b5c9b3d170
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1938:9
  27:     0x55814974d483 - std::sys::unix::thread::Thread::new::thread_start::he8c81c74d5c82445
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7ff76cc74609 - start_thread
  29:     0x7ff76ca42133 - clone
  30:                0x0 - <unknown>
[2m2022-10-09T19:15:46.538536Z[0m [32m INFO[0m [2mmassa_network_worker::network_event::event_impl[0m[2m:[0m Send network event failed An error occurred during channel communication: Failed to send event.
```

**Comment by qdrn** [comment]
`block factory could not get selector draws for slot (period: 22784, thread: 5): `CycleUnavailable`: PoS cycle 178 is needed but is absent from cache` I guess the node is working alone on its clique. It should be detected earlier, no ?

**Comment by qdrn** [comment]
One of our node (testnet3):
```
2022-10-09T19:15:45.968539Z DEBUG massa_network_worker::node_worker: Failed to send NodeEvent due to timeout: NodeEvent(P12vxrYTQzS5TRzxLfFNYxn6PyEsphKWkdqx2mVfEuvJ9sPF43uq, AskedPeerList).
2022-10-09T19:15:45.985641Z DEBUG massa_network_worker::node_worker: Failed to send NodeEvent due to timeout: NodeEvent(P1gEdBVEbRFbBxBtrjcTDDK9JPbJFDay27uiJRE3vmbFAFDKNh7, ReceivedOperationAnnouncements({UfUM145QEZ1HcBgukeYiamM, 3GottYTFwEtHovuPqrgUDPb8, 3PLH4RpY55dXwFWXab9DZWiz, yVi2NvZbfdZEAU6TY2KCs7e, 3F8FWJHBUv5p1mYFSQ8hFYVe, utZifbzQZkQe3LZM1gvj5n1, 39csT4dHDoDa5aSM5TNok16E, 3A5VeyuVauzbvJ6X4B9VVd8D, pqPtiX748W4RPtRY26NvrqS, 9FuVgufDHLWKFmJYG96tXEy, 3KdUnYMDpkxeEwW3mTmJqx65, 2wyTYN9QHxFTPb2icdxviBy1, 31X1Vk22o4V5i6WDJJARmkQx, 25ZzQTQz3iyRe1phCiyre9yC, HKJN2sYzpDEty5hbdYet7JP, 2LgyHgXy8ZxdkiFHqzVhMv3M, kvBb1o137HQ6yrbdU7XX3jf, UGGBogJ6viK8TQX9nX1qbow, 2GA2XEsopAB5LAYsDkoQcxnE, nki3Dyz2tZAWXLvu1cPv6Kw, 2T55EUd6YbeaFYvizaoJ1ny2, Qea8JRg72PNcLaCkW2tkpaq, khtUQmmZCFM2HH6tXGqvPTo, YBdNCg9AsjsrypcJz2xZEPk, ShzghsUmGoWGDUbtjLVmfog, DZFxem8M6XGRHp5DLDjXSVr, 31fkhtH131YT67XqRZx2S2Ro, 2BQsYQMD7DCL7PcRtyiWz9QP, 2B6Bqn6NKdUZMrb7mcH5ipGW, 2acoxW3QNxFtc6peF3rTStZQ, 2QooY9ufcqQKxgqt1sU9LaZv, 25VJp8m7UxVnvqHcVLV7q65t, 2tiEzLeMoEtQatyPjhRocAwh, 2RX3YrXjaU1MayfgznAui2Xj, KiK1NXEGRQGckh7w16AbkZN, 2nbjxQjSfcDuXx69BxVC1qKU, Qi8XshtJ22vRiQXzcwR29uE, 2hFwkhKbM8tJLpcgt5Tzk24f, 3Aeaewpie1WvpKMcerJeZfpL, 3FG1tT8Bn4tCehVCEMV6YyVT, 2FkfvXbEYnNtbnesSUv9nhhD, 2KgXLBiwqU7xFAUqiNem3XQP, ZFqyfcM8Czcb8aXguwnigGx, 3JmBRDVDSdbhr93i5GShwfvQ, 2qqURoPYcxmDbfivHF9V3QDH, 82aDydUdez2aEyaPx5cChhe, 2qLiwc5czQDxLHy3DpNmNpzV, 3MjxVfYZaSoEnaGwWcz2iQoh, 2Pwhhyvb28kSkE5Q42Yt5sWR, 3KGA5hKsRsmwq3wxxrTQTA5A, Gbe9ZTKVEbARvbQsiBRT796, 27XzKKRUt4HesZJyotdfVk8Q, 2PTDLGuQGXUvjA9qXev4M6Nm, F9mdHYa6SudZxKLphr4aC9E, DYEeSPwegCZte78ZLhW7h9R, hN8Ak44KhNCejtoon8m7Zy6, badaKsc1qdhsFvncN7sRowt, 2u7gbYq1B7GLzZrvHy8TmGXy, yNrFXdhqB8TieDgsT3CEEh2, 2ysY8VvySD2MDPcjrF29eHVR, 37C5GKxJmxC8m5zCcDz1Esoj, hntvx1wTsdQbxzBuB6P7H3d, 3MgPbpGTpNuYuDy2iJMJzBfC, 24mwDuEAz4W1xcaeYb9XiDsm, HLcEqBFTdcPr3EZcMpj9Loc, FHMd9Ni5c9MDLkyX5Zm8Jus, cKt5VpEd7njiMZmfE6GauQM, GhJ2Jgb8MErpbHhXyDC2mQK, 3KJsDeAbJ5pumbfWr1KrVj2y, 37bFbXUHDffna5kDXtyJLLbi, 2C3fKvrDvqzMTyTmg1QUAPex, XjiaFTBD5QQvfmXBAs5ob13, 33XzMijZsAGGSH1hgLyy3WWB, 2LJrwh1mPv5xBrZ8Ha1nnMdp, XPnBdFpmgFuRqgqzXTJBMWU, MFp2ToA4Qroh2aszikCA6af, 28FJgmFvLq9wqJ9pKEfoQRYs, 24FwpW4QLps7nchPZsYLYXL9, 9AYNrrhM13M37cqbNUgFE9z, vnXUiijXpXTD6GV4qNugydE, 2ymKdSE6DSuBB6mg7dFn1bRF, 2Y2Vxp2JBSb3Yda8TccSiWVf, 7T39isbWgydxAD499VeKD7P, 3H5rt8rQu7t2dUhtKrJbpkig, 2F1rvy122GHJZQjWPgruiTK3, 3LrMLsMCAdtQ8sPzPp5rBcEK, 2zWxW3fMBysg9p2hkExCYuwf, 2n7WsabEcqHYVjVeR18kfKZE, 2bVh3vgMGpwPwuE3EMTCpUdL, 2LeseMFmmJ9bLEY3L8A1ESB, 2NgvCpTDi5RZEPRWYAj1MsHQ, 2LWCbSJmNngvbTQH57ppMGc1, 2oUmNRkeyz2ZYHkpF8iuqyrr, 2mGScBHwSdggAwLD6QkTcfbZ, 2VxJRdk84sw44RAMNi2vvmXk, 2VdFgKMZJtk53ugPfb19xP48, EKWxRXth6CQkww4EePTBR3w, 2WSsYcdb3DiHezyDuU6UTnU1, rNe8mbk5gNSwgYHwqoiDb6s, 8Y91PSpYaBYsF2eUvWvqAff})).
2022-10-09T19:15:45.985658Z DEBUG massa_network_worker::node_worker: Failed to send NodeEvent due to timeout: NodeEvent(P1hdgsVsd4zkNp8cF1rdqqG6JPRQasAmx12QgJaJHBHFU1fRHEH, ReceivedOperationAnnouncements({UfUM145QEZ1HcBgukeYiamM, 3GottYTFwEtHovuPqrgUDPb8, 3PLH4RpY55dXwFWXab9DZWiz, yVi2NvZbfdZEAU6TY2KCs7e, 3F8FWJHBUv5p1mYFSQ8hFYVe, utZifbzQZkQe3LZM1gvj5n1, 39csT4dHDoDa5aSM5TNok16E, 3A5VeyuVauzbvJ6X4B9VVd8D, pqPtiX748W4RPtRY26NvrqS, 9FuVgufDHLWKFmJYG96tXEy, 3KdUnYMDpkxeEwW3mTmJqx65, 2wyTYN9QHxFTPb2icdxviBy1, 31X1Vk22o4V5i6WDJJARmkQx, 25ZzQTQz3iyRe1phCiyre9yC, HKJN2sYzpDEty5hbdYet7JP, 2LgyHgXy8ZxdkiFHqzVhMv3M, kvBb1o137HQ6yrbdU7XX3jf, UGGBogJ6viK8TQX9nX1qbow, 2GA2XEsopAB5LAYsDkoQcxnE, nki3Dyz2tZAWXLvu1cPv6Kw, 2T55EUd6YbeaFYvizaoJ1ny2, Qea8JRg72PNcLaCkW2tkpaq, khtUQmmZCFM2HH6tXGqvPTo, YBdNCg9AsjsrypcJz2xZEPk, ShzghsUmGoWGDUbtjLVmfog, DZFxem8M6XGRHp5DLDjXSVr, 31fkhtH131YT67XqRZx2S2Ro, 2BQsYQMD7DCL7PcRtyiWz9QP, 2B6Bqn6NKdUZMrb7mcH5ipGW, 2acoxW3QNxFtc6peF3rTStZQ, 2QooY9ufcqQKxgqt1sU9LaZv, 25VJp8m7UxVnvqHcVLV7q65t, 2tiEzLeMoEtQatyPjhRocAwh, 2RX3YrXjaU1MayfgznAui2Xj, KiK1NXEGRQGckh7w16AbkZN, 2nbjxQjSfcDuXx69BxVC1qKU, Qi8XshtJ22vRiQXzcwR29uE, 2hFwkhKbM8tJLpcgt5Tzk24f, 3Aeaewpie1WvpKMcerJeZfpL, 3FG1tT8Bn4tCehVCEMV6YyVT, 2FkfvXbEYnNtbnesSUv9nhhD, 2KgXLBiwqU7xFAUqiNem3XQP, ZFqyfcM8Czcb8aXguwnigGx, 3JmBRDVDSdbhr93i5GShwfvQ, 2qqURoPYcxmDbfivHF9V3QDH, 82aDydUdez2aEyaPx5cChhe, 2qLiwc5czQDxLHy3DpNmNpzV, 3MjxVfYZaSoEnaGwWcz2iQoh, 2Pwhhyvb28kSkE5Q42Yt5sWR, 3KGA5hKsRsmwq3wxxrTQTA5A, Gbe9ZTKVEbARvbQsiBRT796, 27XzKKRUt4HesZJyotdfVk8Q, 2PTDLGuQGXUvjA9qXev4M6Nm, F9mdHYa6SudZxKLphr4aC9E, DYEeSPwegCZte78ZLhW7h9R, hN8Ak44KhNCejtoon8m7Zy6, badaKsc1qdhsFvncN7sRowt, 2u7gbYq1B7GLzZrvHy8TmGXy, yNrFXdhqB8TieDgsT3CEEh2, 2ysY8VvySD2MDPcjrF29eHVR, 37C5GKxJmxC8m5zCcDz1Esoj, hntvx1wTsdQbxzBuB6P7H3d, 3MgPbpGTpNuYuDy2iJMJzBfC, 24mwDuEAz4W1xcaeYb9XiDsm, HLcEqBFTdcPr3EZcMpj9Loc, FHMd9Ni5c9MDLkyX5Zm8Jus, cKt5VpEd7njiMZmfE6GauQM, GhJ2Jgb8MErpbHhXyDC2mQK, 3KJsDeAbJ5pumbfWr1KrVj2y, 37bFbXUHDffna5kDXtyJLLbi, 2C3fKvrDvqzMTyTmg1QUAPex, XjiaFTBD5QQvfmXBAs5ob13, 33XzMijZsAGGSH1hgLyy3WWB, 2LJrwh1mPv5xBrZ8Ha1nnMdp, XPnBdFpmgFuRqgqzXTJBMWU, MFp2ToA4Qroh2aszikCA6af, 28FJgmFvLq9wqJ9pKEfoQRYs, 24FwpW4QLps7nchPZsYLYXL9, 9AYNrrhM13M37cqbNUgFE9z, vnXUiijXpXTD6GV4qNugydE, 2ymKdSE6DSuBB6mg7dFn1bRF, 2Y2Vxp2JBSb3Yda8TccSiWVf, 7T39isbWgydxAD499VeKD7P, 3H5rt8rQu7t2dUhtKrJbpkig, 2F1rvy122GHJZQjWPgruiTK3, 3LrMLsMCAdtQ8sPzPp5rBcEK, 2zWxW3fMBysg9p2hkExCYuwf, 2n7WsabEcqHYVjVeR18kfKZE, 2bVh3vgMGpwPwuE3EMTCpUdL, 2LeseMFmmJ9bLEY3L8A1ESB, 2NgvCpTDi5RZEPRWYAj1MsHQ, 2LWCbSJmNngvbTQH57ppMGc1, 2oUmNRkeyz2ZYHkpF8iuqyrr, 2mGScBHwSdggAwLD6QkTcfbZ, 2VxJRdk84sw44RAMNi2vvmXk, 2VdFgKMZJtk53ugPfb19xP48, EKWxRXth6CQkww4EePTBR3w, 2WSsYcdb3DiHezyDuU6UTnU1, rNe8mbk5gNSwgYHwqoiDb6s, 8Y91PSpYaBYsF2eUvWvqAff})).
2022-10-09T19:15:46.000223Z DEBUG massa_execution_worker::worker: Execution loop triggered, input_data = stop=false, finalized={}, blockclique=None, readonly=RequestQueue { max_items: 10000, queue: [] }
2022-10-09T19:15:46.000260Z DEBUG massa_execution_worker::execution: execute_candidate_slot: executing slot=(period: 22784, thread: 0) target=None
thread '<unnamed>' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(178)', massa-execution-worker/src/execution.rs:889:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-10-09T19:15:46.000585Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 22784, thread: 4): `CycleUnavailable`: PoS cycle 178 is needed but is absent from cache
```

**Comment by qdrn** [comment]
I'm closing since it's a consequence of other problems that have their own issue.
