### ISSUE TITLE
Node Crash (15.1)

### ISSUE THREAD

**Issue by Unrender** [massalabs/massa#3152]
Hi,

Since yesterday, my node has crashed 4 times.
I use the binary on MacOS Monterey 12.6
The node is launched either directly from the terminal, or from Screen GNU in the terminal.
The node crashes in both cases.

The end of the log file : 

`[2m2022-10-11T15:34:04.420986Z[0m [33m WARN[0m [2mmassa_protocol_worker::protocol_network[0m[2m:[0m Node P12wDViuRuLRKkF68N9CFKHUM1qRUpNA8VCq7CxfLkKfSBZaRJs1 sent us full operations but we don't have the block id 2jC4YUMMjSSXGX192uR6xRbV2up59zCccke1QAXbFXoGTcUzmM in our wishlist.

[2m2022-10-11T15:58:21.002411Z[0m [32m INFO[0m [2mmassa_consensus_worker::consensus_worker[0m[2m:[0m Started cycle 48

[2m2022-10-11T15:58:21.002444Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 10): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002452Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 11): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002456Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 12): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002459Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 13): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002464Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 14): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002467Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 15): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002471Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 16): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002474Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 17): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002477Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 18): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002480Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 19): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002483Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 20): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002486Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 21): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002489Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 22): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002492Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 23): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002496Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 24): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002499Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 25): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002503Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 26): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.002411Z[0m [33m WARN[0m [2mmassa_factory_worker::block_factory[0m[2m:[0m block factory could not get selector draws for slot (period: 6181, thread: 10): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.501726Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 6181, thread: 27): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

[2m2022-10-11T15:58:21.501831Z[0m [33m WARN[0m [2mmassa_factory_worker::block_factory[0m[2m:[0m block factory could not get selector draws for slot (period: 6181, thread: 11): `CycleUnavailable`: PoS cycle 48 is needed but is absent from cache

thread '<unnamed>' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(48)', massa-execution-worker/src/execution.rs:888:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Full log file is attached.

Thank you ;)
[logs.txt](https://github.com/massalabs/massa/files/9759069/logs.txt)

**Comment by Unrender** [comment]
Just for information, I launched the node using docker and rykcod/massa container, and the node crashed again. The log shows the same things :
`2022-10-11T22:46:20.218692Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 7711, thread: 24): `CycleUnavailable`: PoS cycle 60 is needed but is absent from cache

2022-10-11T22:46:20.219303Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 7711, thread: 8): `CycleUnavailable`: PoS cycle 60 is needed but is absent from cache
thread '<unnamed>' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(60)', massa-execution-worker/src/execution.rs:888:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by h4ckm1n-dev** [comment]
My node crashed at 6 o clock this night

15.1 docker image

Log from the 13/10/2022

`2022-10-13T04:12:50.340307Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.341462Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.342620Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.344259Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.345642Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.346853Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.348160Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.349524Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.350783Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.351362Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.352585Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.353928Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.355093Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.356840Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.358045Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.359210Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.360412Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.361663Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.362947Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.364181Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.369037Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.370897Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.372186Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.374703Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.376214Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.378427Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.381356Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.382542Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.383684Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.384810Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.385935Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.388134Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.390492Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.392288Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.394274Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.395456Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.396605Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.397749Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.398528Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.400570Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.401225Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.402411Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.403578Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.404345Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.405574Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.406161Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2022-10-13T04:12:50.500320Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 5): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:51.000455Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 6): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:51.500672Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 7): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:52.001382Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 8): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:52.500552Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 9): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:53.000798Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 10): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:53.500952Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 11): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:54.001681Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 12): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:54.500816Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 13): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:55.002036Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 14): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:55.500188Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 15): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:56.000389Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 16): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:56.003963Z  INFO massa_consensus_worker::consensus_worker: Started cycle 112
2022-10-13T04:12:56.007951Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 14336, thread: 0): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:56.500346Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 14336, thread: 1): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:56.500614Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 17): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:57.000646Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 14336, thread: 2): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:57.000789Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 18): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:57.500782Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 14336, thread: 3): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:57.501046Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 19): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:58.000268Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 14336, thread: 20): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
2022-10-13T04:12:58.000925Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 14336, thread: 4): `CycleUnavailable`: PoS cycle 112 is needed but is absent from cache
thread '<unnamed>' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(112)', massa-execution-worker/src/execution.rs:888:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by Unrender** [comment]
Don't know if it can help but here is the message I have when my node crashes. This time, I launched the node directly from the terminal of MacOs (without using Docker) :
`thread '<unnamed>' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(138)', massa-execution-worker/src/execution.rs:888:18
stack backtrace:
   0:        0x105236b42 - std::backtrace_rs::backtrace::libunwind::trace::hd197e831e8e1e239
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:        0x105236b42 - std::backtrace_rs::backtrace::trace_unsynchronized::hfe67c6a702a14f07
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x105236b42 - std::sys_common::backtrace::_print_fmt::h996b70bd2d2901e9
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x105236b42 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb20914c499d31c38
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x10525567a - core::fmt::write::hde32ea8b71bc74bf
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/core/src/fmt/mod.rs:1209:17
   5:        0x10523093c - std::io::Write::write_fmt::had725afe4b7fe5b5
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/io/mod.rs:1679:15
   6:        0x105238aab - std::sys_common::backtrace::_print::hab50125d72d8f93c
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x105238aab - std::sys_common::backtrace::print::ha102bc5c439e0c15
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x105238aab - std::panicking::default_hook::{{closure}}::h01d9124b715c297e
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:267:22
   9:        0x1052387b7 - std::panicking::default_hook::hb4b0213be72b178c
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:286:9
  10:        0x104539f81 - massa_node::main::{{closure}}::{{closure}}::h6505869399a5d016
  11:        0x1052391aa - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd896a4e2f9467de4
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/alloc/src/boxed.rs:1952:9
  12:        0x1052391aa - std::panicking::rust_panic_with_hook::h323c29bd9c39f239
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:673:13
  13:        0x105239013 - std::panicking::begin_panic_handler::{{closure}}::hc7d57f9e201d8799
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:560:13
  14:        0x105236fd8 - std::sys_common::backtrace::__rust_end_short_backtrace::h375d5891bdd8117e
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/sys_common/backtrace.rs:138:18
  15:        0x105238cdd - rust_begin_unwind
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/panicking.rs:556:5
  16:        0x1052f5253 - core::panicking::panic_fmt::hcc0951f445535a3b
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/core/src/panicking.rs:142:14
  17:        0x1052f53b5 - core::result::unwrap_failed::h298adaeca20863d8
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/core/src/result.rs:1791:5
  18:        0x104b43b4e - massa_execution_worker::execution::ExecutionState::execute_slot::hff9f4e924a73b19f
  19:        0x104b45207 - massa_execution_worker::execution::ExecutionState::execute_candidate_slot::h47f66f05a0f19cf4
  20:        0x104b7b6ba - massa_execution_worker::worker::ExecutionThread::main_loop::{{closure}}::ha9d2cfebe27d8aee
  21:        0x104b7b249 - massa_execution_worker::slot_sequencer::SlotSequencer::run_task_with::h46223fa90e40ecdf
  22:        0x104b5a3cc - massa_execution_worker::worker::ExecutionThread::main_loop::h4587547654098040
  23:        0x104b4a6de - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c439d7e06aeb157
  24:        0x104b61cf8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1a975275ef1a58d2
  25:        0x10523c1d7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::had078943fcc4ea10
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/alloc/src/boxed.rs:1938:9
  26:        0x10523c1d7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb90561df3fca512c
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/alloc/src/boxed.rs:1938:9
  27:        0x10523c1d7 - std::sys::unix::thread::Thread::new::thread_start::h6aed21cd37a2e62a
                               at /rustc/81f391930301afbc121b7c468138069daa354bf8/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7ff80d1d74e1 - __pthread_start`

**Comment by damip** [comment]
A tentative correction to this class of problems was done here: https://github.com/massalabs/massa

**Comment by Unrender** [comment]
Oh great ! Thank you. I'm gonna to check that ;)

**Comment by damip** [comment]
Should be corrected in testnet 16. Will reopen if the problem appears again
