### ISSUE TITLE
thread 'execution' panicked at 'couldn't get the expected block producer for a missed slot'

### ISSUE THREAD

**Issue by chriscooper1983** [massalabs/massa#3217]
**Describe the bug**
The node crashed, so i tried to reconnect, but fails with error: thread 'execution' panicked at 'couldn't get the expected block producer for a missed slot'.

**To Reproduce**
1) open cli
2) ssh root@this.is.my.ip
3) screen -S node
4) cd massa/massa-node
5) RUST_BACKTRACE=full cargo run --release -- -p 123 |& tee logs.txt 

**Expected behavior**
Node tries to connect with bootstrap servers for about half an hour, and crashed with error from above.

- OS: Debian 11.5 minimal (running in LXC Container inside Proxmox 7.2.7)
- Version; 16

**Additional context**
thread 'execution' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(615)', massa-execution-worker/src/[execution.rs:889](http://execution.rs:889/):18
stack backtrace:
   0:     0x55e567961be0 - std::backtrace_rs::backtrace::libunwind::trace::h88aa58d3404f3010
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/../../backtrace/src/backtrace/[libunwind.rs:93](http://libunwind.rs:93/):5
   1:     0x55e567961be0 - std::backtrace_rs::backtrace::trace_unsynchronized::h242befdc4043504a
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/../../backtrace/src/backtrace/[mod.rs:66](http://mod.rs:66/):5
   2:     0x55e567961be0 - std::sys_common::backtrace::_print_fmt::ha7c0a15b66663a16
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/sys_common/[backtrace.rs:65](http://backtrace.rs:65/):5
   3:     0x55e567961be0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h89b35c10c92ec459
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/sys_common/[backtrace.rs:44](http://backtrace.rs:44/):22
   4:     0x55e56798626e - core::fmt::write::h126889db550b7631
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/fmt/[mod.rs:1209](http://mod.rs:1209/):17
   5:     0x55e56795c235 - std::io::Write::write_fmt::h8104868e0509eb9f
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/io/[mod.rs:1682](http://mod.rs:1682/):15
   6:     0x55e5679619a5 - std::sys_common::backtrace::_print::hbf551d014396b2ea
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/sys_common/[backtrace.rs:47](http://backtrace.rs:47/):5
   7:     0x55e5679619a5 - std::sys_common::backtrace::print::h8d815730635a8daf
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/sys_common/[backtrace.rs:34](http://backtrace.rs:34/):9
   8:     0x55e56796358f - std::panicking::default_hook::{{closure}}::h1053916ccba706ee
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/[panicking.rs:267](http://panicking.rs:267/):22
   9:     0x55e5679632ca - std::panicking::default_hook::he07a78437e20ff6f
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/[panicking.rs:286](http://panicking.rs:286/):9
  10:     0x55e566ca82ce - massa_node::run::{{closure}}::{{closure}}::h455e0da09e70f7db
  11:     0x55e567963cad - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h99a47947a6cffbcd
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/alloc/src/[boxed.rs:2001](http://boxed.rs:2001/):9
  12:     0x55e567963cad - std::panicking::rust_panic_with_hook::h69e76337c387720d
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/[panicking.rs:692](http://panicking.rs:692/):13
  13:     0x55e567963a27 - std::panicking::begin_panic_handler::{{closure}}::hc4fc18b4ec5ec8a9
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/[panicking.rs:579](http://panicking.rs:579/):13
  14:     0x55e56796208c - std::sys_common::backtrace::__rust_end_short_backtrace::h29d7596fa29754db
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/sys_common/[backtrace.rs:137](http://backtrace.rs:137/):18
  15:     0x55e567963742 - rust_begin_unwind
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/[panicking.rs:575](http://panicking.rs:575/):5
  16:     0x55e566af3983 - core::panicking::panic_fmt::h12ff66c6f3be7082
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/[panicking.rs:65](http://panicking.rs:65/):14
  17:     0x55e566af3c43 - core::result::unwrap_failed::h170dda57c65111bb
                               at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/[result.rs:1791](http://result.rs:1791/):5
  18:     0x55e5672f1993 - massa_execution_worker::execution::ExecutionState::execute_slot::hf9da8da473a73b30

**Comment by AurelienFT** [comment]
Hello, thanks for your report. We made a fix on test.17, It seems that we don't reproduce on this testnet so I'm closing.
