### ISSUE TITLE
WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 51456, thread: 4): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache

### ISSUE THREAD

**Issue by canf1yyo** [massalabs/massa#3321]
![2022-12-10_17-58-13](https://user-images.githubusercontent.com/108034322/206861693-29895302-9244-4348-9d40-4491cf0137aa.png)
![2022-12-10_17-57-43](https://user-images.githubusercontent.com/108034322/206861698-a9dc196a-3b15-428d-9c19-2af94038a6bf.png)

2022-12-10T12:41:16.058980Z  INFO massa_protocol_worker::protocol_network: Connection closed with P12RuBQaSjkkM6TxbE7JsVZV614FvV599rYVWkzwKYCLkgJEgKoy
2022-12-10T12:41:23.791274Z  INFO massa_protocol_worker::protocol_network: Connected to node P1h6qhq1kskujZ4n3eWrefwc5BH7dSiXUNLh7s96auRJXJpRb3b
2022-12-10T12:41:29.000674Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 0): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:29.500789Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 1): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:30.000902Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 2): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:30.501016Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 3): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:31.000117Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 4): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:31.500224Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 5): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:32.000298Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 6): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:32.500405Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 7): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:33.000519Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 8): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:33.500620Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 9): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:34.000718Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 10): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:34.500822Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 11): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:35.000923Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 12): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:35.501026Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 13): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:36.000129Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 14): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:36.500204Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 15): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:37.000306Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 16): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:37.000534Z  INFO massa_consensus_worker::worker::main_loop: Started cycle 402
2022-12-10T12:41:37.000695Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 51456, thread: 0): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:37.500418Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 17): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:37.500766Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 51456, thread: 1): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:38.000526Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 18): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:38.000865Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 51456, thread: 2): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:38.066798Z  INFO massa_protocol_worker::protocol_network: Connection closed with P1h6qhq1kskujZ4n3eWrefwc5BH7dSiXUNLh7s96auRJXJpRb3b
2022-12-10T12:41:38.500631Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 19): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:38.500933Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 51456, thread: 3): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
thread 'execution' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(402)', massa-execution-worker/src/execution.rs:886:18
stack backtrace:
2022-12-10T12:41:39.000733Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 51456, thread: 20): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
2022-12-10T12:41:39.000999Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 51456, thread: 4): `CycleUnavailable`: PoS cycle 402 is needed but is absent from cache
   0:     0x5653351d7de0 - std::backtrace_rs::backtrace::libunwind::trace::he4d5f2c13fd7ea58
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5653351d7de0 - std::backtrace_rs::backtrace::trace_unsynchronized::ha872462b0d7f1993
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5653351d7de0 - std::sys_common::backtrace::_print_fmt::hfa57ea34975e92c8
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5653351d7de0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf4fb6a2aa638ae6
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5653351fc3ae - core::fmt::write::h556296da8255a0fe
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/core/src/fmt/mod.rs:1209:17
   5:     0x5653351d2645 - std::io::Write::write_fmt::h1e63bc45d9e0b177
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/io/mod.rs:1682:15
   6:     0x5653351d7ba5 - std::sys_common::backtrace::_print::h18ecb2198a8971d0
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5653351d7ba5 - std::sys_common::backtrace::print::he62f784f6f099fe2
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5653351d975f - std::panicking::default_hook::{{closure}}::h220c4bc545c14f7e
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:267:22
   9:     0x5653351d949a - std::panicking::default_hook::hc6a46490400a51ce
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:286:9
  10:     0x5653343eaade - massa_node::run::{{closure}}::{{closure}}::h859793957d960adc
  11:     0x5653351d9e7d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hba54d23f8fd826e2
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/alloc/src/boxed.rs:2032:9
  12:     0x5653351d9e7d - std::panicking::rust_panic_with_hook::hec8b21fa74280350
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:692:13
  13:     0x5653351d9bf7 - std::panicking::begin_panic_handler::{{closure}}::hfc7a6bbbe087d67f
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:579:13
  14:     0x5653351d828c - std::sys_common::backtrace::__rust_end_short_backtrace::h9522cd483b462760
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x5653351d9912 - rust_begin_unwind
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:575:5
  16:     0x5653342273d3 - core::panicking::panic_fmt::hed336b84331644c6
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/core/src/panicking.rs:65:14
  17:     0x565334227693 - core::result::unwrap_failed::h72a46b524ecd9480
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/core/src/result.rs:1791:5
  18:     0x565334a2bd65 - massa_execution_worker::execution::ExecutionState::execute_slot::h3a1126ee5d988561
  19:     0x565334a2d4b6 - massa_execution_worker::execution::ExecutionState::execute_candidate_slot::hb6ff9307ac6d36fd
  20:     0x565334a06a8f - massa_execution_worker::worker::ExecutionThread::main_loop::{{closure}}::h87d43e546cffecb6
  21:     0x565334a01bd7 - massa_execution_worker::slot_sequencer::SlotSequencer::run_task_with::hb5665f189edd06c4
  22:     0x5653349f3825 - massa_execution_worker::worker::ExecutionThread::main_loop::h213dbb0f5c6a4a5a
  23:     0x565334a1359a - std::sys_common::backtrace::__rust_begin_short_backtrace::h566bbcc862393e20
  24:     0x5653349f4e5e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hca07f0b77556e253
  25:     0x5653351dce53 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb9beccc25c64a001
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/alloc/src/boxed.rs:2000:9
  26:     0x5653351dce53 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hde98428e87ac1a81
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/alloc/src/boxed.rs:2000:9
  27:     0x5653351dce53 - std::sys::unix::thread::Thread::new::thread_start::h2ef156d73deb51c1
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7fbc5fa7a609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  29:     0x7fbc5f848133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  30:                0x0 - <unknown>

**Comment by AurelienFT** [comment]
Hello, 

Thanks for your reporting.
We see in your logs that you disconnected and connected from a lot of peoples before this crash. This crash happens when you didn't received any blocks in the last cycle. It's due to a desynchronization that you had in the past (possibly a disconnection or internet instability) and so you have missed some information. This information missed make your node and the others continue in two differents states of the blockchain and so you can't connect to anyone else.
If you are not connected you don't receive any block and so one cycle after you have this error.

We need to improve the detection of desynchronization to have more explicit error and send it more faster after the real time of the desynchronization.

You need to delete the content of your `massa-node/storage` folder and restart your node.
