### ISSUE TITLE
Thread 'main' panicked  at range end index 33

### ISSUE THREAD

**Issue by Megavolv** [massalabs/massa#3325]
**Describe the bug**
thread 'main' panicked at 'range end index 33 out of range for slice of length 0', massa-ledger-exports/src/key.rs:92:24

**Desktop (please complete the following information):**

Linux, Ubuntu.

**Comment by Ben-PH** [comment]
Got the same panic it would seem:
```
2022-12-13T00:15:30.757440Z  INFO massa_node: Node version : TEST.17.2
2022-12-13T00:15:30.782959Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.23.120:31245
2022-12-13T00:28:11.630839Z  WARN massa_bootstrap::client: Error while bootstrapping: io error: final state error: ledger error: get_state_changes_part given slot is overflowing history.
2022-12-13T00:28:11.630939Z  INFO massa_bootstrap::client: Bootstrap from server 158.69.23.120:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:29:11.632438Z  INFO massa_bootstrap::client: Start bootstrapping from 51.75.60.228:31245
2022-12-13T00:29:11.734449Z  WARN massa_bootstrap::client: Error received from bootstrap server: Bootstrap failed because the bootstrap server currently has no slots available.
2022-12-13T00:29:11.734588Z  INFO massa_bootstrap::client: Bootstrap from server 51.75.60.228:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:30:11.735772Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.120.215:31245
2022-12-13T00:30:11.939354Z  WARN massa_bootstrap::client: Error received from bootstrap server: Bootstrap failed because the bootstrap server currently has no slots available.
2022-12-13T00:30:11.939434Z  INFO massa_bootstrap::client: Bootstrap from server 158.69.120.215:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:31:11.940357Z  INFO massa_bootstrap::client: Start bootstrapping from 198.27.74.5:31245
2022-12-13T00:31:12.341012Z  WARN massa_bootstrap::client: Error while bootstrapping: io error: Connection reset by peer (os error 104)
2022-12-13T00:31:12.341094Z  INFO massa_bootstrap::client: Bootstrap from server 198.27.74.5:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:32:12.342623Z  INFO massa_bootstrap::client: Start bootstrapping from 149.202.86.103:31245
2022-12-13T00:32:12.390993Z  WARN massa_bootstrap::client: Error received from bootstrap server: Your last bootstrap on this server was 11h 32m 44s 50ms 365us 164ns ago and you have to wait before retrying.
2022-12-13T00:32:12.391112Z  INFO massa_bootstrap::client: Bootstrap from server 149.202.86.103:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:33:12.392896Z  INFO massa_bootstrap::client: Start bootstrapping from 198.27.74.52:31245
2022-12-13T00:33:12.789689Z  WARN massa_bootstrap::client: Error while bootstrapping: `massa_signature` error Signature error : Signature verification failed: signature error: Verification equation was not satisfied
2022-12-13T00:33:12.789753Z  INFO massa_bootstrap::client: Bootstrap from server 198.27.74.52:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:34:12.790597Z  INFO massa_bootstrap::client: Start bootstrapping from 54.36.174.177:31245
2022-12-13T00:34:12.886801Z  WARN massa_bootstrap::client: Error received from bootstrap server: Your last bootstrap on this server was 11h 27m 7s 968ms 228us 789ns ago and you have to wait before retrying.
2022-12-13T00:34:12.886889Z  INFO massa_bootstrap::client: Bootstrap from server 54.36.174.177:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:35:12.888561Z  INFO massa_bootstrap::client: Start bootstrapping from 149.202.89.125:31245
2022-12-13T00:35:12.941518Z  WARN massa_bootstrap::client: Error received from bootstrap server: Your last bootstrap on this server was 10h 3m 33s 648ms 941us 370ns ago and you have to wait before retrying.
2022-12-13T00:35:12.941605Z  INFO massa_bootstrap::client: Bootstrap from server 149.202.89.125:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:36:12.942412Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.23.120:31245
2022-12-13T00:36:13.143137Z  WARN massa_bootstrap::client: Error received from bootstrap server: Your last bootstrap on this server was 11h 39m 17s 844ms 313us 402ns ago and you have to wait before retrying.
2022-12-13T00:36:13.143230Z  INFO massa_bootstrap::client: Bootstrap from server 158.69.23.120:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:37:13.144952Z  INFO massa_bootstrap::client: Start bootstrapping from 51.75.60.228:31245
2022-12-13T00:37:13.236790Z  WARN massa_bootstrap::client: Error received from bootstrap server: Bootstrap failed because the bootstrap server currently has no slots available.
2022-12-13T00:37:13.236879Z  INFO massa_bootstrap::client: Bootstrap from server 51.75.60.228:31245 failed. Your node will try to bootstrap from another server in 1m.
2022-12-13T00:38:13.238577Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.120.215:31245
thread 'main' panicked at 'range end index 33 out of range for slice of length 0', massa-ledger-exports/src/key.rs:92:24
stack backtrace:
   0:     0x55e62c46b3f0 - std::backtrace_rs::backtrace::libunwind::trace::h1c0259b0e54a0ec7
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e62c46b3f0 - std::backtrace_rs::backtrace::trace_unsynchronized::hef156fa43f257fff
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e62c46b3f0 - std::sys_common::backtrace::_print_fmt::h14c30be4df8a453b
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55e62c46b3f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6bc9ef49ac207d73
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e62c48f95e - core::fmt::write::h670e2d8b480677bf
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/core/src/fmt/mod.rs:1209:17
   5:     0x55e62c465a45 - std::io::Write::write_fmt::h96cca416c9a25a8f
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/io/mod.rs:1682:15
   6:     0x55e62c46b1b5 - std::sys_common::backtrace::_print::h209eac292799b1d3
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55e62c46b1b5 - std::sys_common::backtrace::print::h02ded1b579fe176b
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55e62c46cd9f - std::panicking::default_hook::{{closure}}::h8511971ca7cce5b1
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:267:22
   9:     0x55e62c46cada - std::panicking::default_hook::h8bc8dfd96a84f923
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:286:9
  10:     0x55e62b67691e - massa_node::run::{{closure}}::{{closure}}::hab582bbd50c37651
  11:     0x55e62c46d4bd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0da21114ecfdabf5
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/alloc/src/boxed.rs:2032:9
  12:     0x55e62c46d4bd - std::panicking::rust_panic_with_hook::h9f2bfce9b4c1819d
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:692:13
  13:     0x55e62c46d237 - std::panicking::begin_panic_handler::{{closure}}::h167b5f05f9579bc1
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:579:13
  14:     0x55e62c46b89c - std::sys_common::backtrace::__rust_end_short_backtrace::h99451dfb597ab6ac
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x55e62c46cf52 - rust_begin_unwind
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:575:5
  16:     0x55e62b4aba93 - core::panicking::panic_fmt::hf9d641a075644e68
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/core/src/panicking.rs:65:14
  17:     0x55e62c4921c2 - core::slice::index::slice_end_index_len_fail_rt::hb0a82dd16debf098
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/core/src/slice/index.rs:76:5
  18:     0x55e62b4abd77 - core::slice::index::slice_end_index_len_fail::h7cd795627424ac95
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/core/src/slice/index.rs:69:9
  19:     0x55e62c1d3a5b - <massa_ledger_exports::key::KeySerializer as massa_serialization::Serializer<alloc::vec::Vec<u8>>>::serialize::h61831260be5d7351
  20:     0x55e62bfffb74 - <massa_models::streaming_step::StreamingStepSerializer<T,ST> as massa_serialization::Serializer<massa_models::streaming_step::StreamingStep<T>>>::serialize::h000646763f6e93d6
  21:     0x55e62bffcdb9 - <massa_bootstrap::messages::BootstrapClientMessageSerializer as massa_serialization::Serializer<massa_bootstrap::messages::BootstrapClientMessage>>::serialize::h2faefb2d5f1f027d
  22:     0x55e62b664fb9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he0fe49393df6f3b3
  23:     0x55e62b544302 - <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll::hfb3817ff706f5625
  24:     0x55e62b5c9749 - massa_bootstrap::client::bootstrap_from_server::{{closure}}::hcf2148652f2ea303
  25:     0x55e62b5cf63c - massa_bootstrap::client::get_state::{{closure}}::h064c95a6ce01fdef
  26:     0x55e62b544d58 - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h3ebb936471ca9ef5
  27:     0x55e62b66a83b - massa_node::launch::{{closure}}::hd6a5923a980dd646
  28:     0x55e62b63efca - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1cce9b079f10a377
  29:     0x55e62b53fab2 - tokio::runtime::park::CachedParkThread::block_on::h8e14eda8e34f8fc0
  30:     0x55e62b571769 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hd9d7022dd15ece07
  31:     0x55e62b5adc9f - massa_node::main::h8596c719453ba6b6
  32:     0x55e62b54c563 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd94814bc1c111e0f
  33:     0x55e62b597a8d - std::rt::lang_start::{{closure}}::h9b73d1795eb9b5f5
  34:     0x55e62c45f17b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h826597257e3879b4
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/core/src/ops/function.rs:609:13
  35:     0x55e62c45f17b - std::panicking::try::do_call::h430bec0379289c43
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:483:40
  36:     0x55e62c45f17b - std::panicking::try::h6dcfddfaa45ef9c8
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:447:19
  37:     0x55e62c45f17b - std::panic::catch_unwind::hf670f144d5ff2fff
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panic.rs:137:14
  38:     0x55e62c45f17b - std::rt::lang_start_internal::{{closure}}::hd340bf1185ef778e
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/rt.rs:148:48
  39:     0x55e62c45f17b - std::panicking::try::do_call::h2701d713e51084f1
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:483:40
  40:     0x55e62c45f17b - std::panicking::try::hc887b64ee176e8cc
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panicking.rs:447:19
  41:     0x55e62c45f17b - std::panic::catch_unwind::h2f284887296a635a
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/panic.rs:137:14
  42:     0x55e62c45f17b - std::rt::lang_start_internal::ha964f4f4b3c537bd
                               at /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/std/src/rt.rs:148:20
  43:     0x55e62b5adf35 - main
  44:     0x7f57340cad90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  45:     0x7f57340cae40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  46:     0x55e62b4d71d5 - _start
  47:                0x0 - <unknown>
```

**Comment by AurelienFT** [comment]
Fixed in https://github.com/massalabs/massa/pull/3329 Will be in the next release.

Thanks everyone for your report
