### ISSUE TITLE
Error in test 18.00 ( thread '<unnamed>' panicked at 'assertion failed: `(left != right) )

### ISSUE THREAD

**Issue by ErkanDERELI** [massalabs/massa#3393]
Server = Dell R710
Cpu = Intel Xeon X5675
OS = ubuntu 20.04
Bandwidth = Uplink 8 Downlink 100
VM = 12 core 8GB Ram 35G Hdd

After the 18th test started, I got an error like the one below.

A separate massa node is running on my same server with different ISP. I got an error from him at the same `minute.`

![prxmxmassa](https://user-images.githubusercontent.com/75272957/211351925-4b115447-9631-4968-a0cb-6d9f03e245f4.jpg)
![mass1](https://user-images.githubusercontent.com/75272957/211351953-8cf721f0-3d5e-4c8e-bf46-dcd474c28e85.jpg)

`
2023-01-09T09:06:14.930361Z  INFO massa_final_state::final_state: final_state hash at slot (period: 29044, thread: 28): Zkp4LU4XffQLpLKq5Jga1rfUjqaKsjzXFw6pLdrV9gmc39KgR
2023-01-09T09:06:14.932157Z  INFO massa_final_state::final_state: final_state hash at slot (period: 29044, thread: 29): 2AUgkzedPczeZVHAmBQcjNEJWD1zewPfyMtHxNDkWABx7zaRN
2023-01-09T09:06:14.933758Z  INFO massa_final_state::final_state: final_state hash at slot (period: 29044, thread: 30): sqdkhN5Fo2u4HJ9WHCKiBQj4fLSmAcRQu6rh3zCgRPZ7ho3Yv
2023-01-09T09:06:14.935538Z  INFO massa_final_state::final_state: final_state hash at slot (period: 29044, thread: 31): cG1K4yhtgmaVn8jYDKzhiAfj82bsw4hbmuj86sRDJRN7GPFtU
2023-01-09T09:06:17.339851Z  INFO massa_final_state::final_state: final_state hash at slot (period: 29045, thread: 0): i1tZRsTXzL1MobLu22tByKM4pJxaBnJmKipUEALzt6vM72Wzs
2023-01-09T09:06:17.341711Z  INFO massa_final_state::final_state: final_state hash at slot (period: 29045, thread: 1): 2pV2oH4KKUdFfoH3sTtvVwP7nXMGiJmmnNtJ7gdwj398Evgzwy
2023-01-09T09:06:17.463105Z  INFO massa_protocol_worker::protocol_network: Connected to node N1pQpfpVwyYwFaFcccYrjEKanzCUUqxXNiffpTgdtU1bTZd91Yd
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `XMM3`,
 right: `XMM3`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/emitter_x64.rs:1752:40
stack backtrace:
   0:     0x5590784e244a - std::backtrace_rs::backtrace::libunwind::trace::hfbeb4b2b22d738bc
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5590784e244a - std::backtrace_rs::backtrace::trace_unsynchronized::hcb078a4cbf58419c
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5590784e244a - std::sys_common::backtrace::_print_fmt::hac5b7a2e71b9d4a2
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5590784e244a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39740540205245e8
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5590785063fe - core::fmt::write::hbf78108acb1498ba
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/core/src/fmt/mod.rs:1208:17
   5:     0x5590784dcc35 - std::io::Write::write_fmt::h17c5408264a7c236
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/io/mod.rs:1682:15
   6:     0x5590784e2215 - std::sys_common::backtrace::_print::h3fcfa786bd91d49d
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5590784e2215 - std::sys_common::backtrace::print::h9f68dbc9130a1e43
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5590784e3d4f - std::panicking::default_hook::{{closure}}::h2f0941ce27a29acf
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:267:22
   9:     0x5590784e3a8b - std::panicking::default_hook::h5fc054efab50e987
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:286:9
  10:     0x5590774c1c4e - massa_node::run::{{closure}}::{{closure}}::ha95c2d09f1d54c1d
  11:     0x5590784e447d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha98456fc8f91c853
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/alloc/src/boxed.rs:2032:9
  12:     0x5590784e447d - std::panicking::rust_panic_with_hook::h21670202cf8178d4
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:692:13
  13:     0x5590784e41f9 - std::panicking::begin_panic_handler::{{closure}}::h92d41791709d0592
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:579:13
  14:     0x5590784e28fc - std::sys_common::backtrace::__rust_end_short_backtrace::hadd55dccca5a9b00
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x5590784e3f02 - rust_begin_unwind
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:575:5
  16:     0x559077452f43 - core::panicking::panic_fmt::h5499993c5ba4eb21
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/core/src/panicking.rs:64:14
  17:     0x55907745325f - core::panicking::assert_failed_inner::h755b8247bc2c2b0f
  18:     0x55907742485b - core::panicking::assert_failed::h20b00660f3531d85
  19:     0x559078053cdc - <wasmer_compiler_singlepass::machine_x64::AssemblerX64 as wasmer_compiler_singlepass::emitter_x64::EmitterX64>::emit_vmulsd::h974d662091c9625d
  20:     0x55907807269e - wasmer_compiler_singlepass::machine_x64::MachineX86_64::emit_relaxed_avx::h06fb3bb1802be3f0
  21:     0x559078013530 - wasmer_compiler_singlepass::codegen::FuncGen<M>::feed_operator::h1e959ee3ae6dc1cf
  22:     0x559077fa52df - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h8a03cbddb2e467f7
  23:     0x5590781345c7 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::h72ad402c324e00b0
  24:     0x5590780b4882 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h760ca101142e8703
  25:     0x5590780bc1cc - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  26:     0x5590780b1492 - rayon_core::registry::in_worker::hcb7bd958f38cc0d0
  27:     0x5590780bc2a1 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  28:     0x559077fac0d7 - rayon_core::job::StackJob<L,F,R>::run_inline::h6423057f519710de
  29:     0x5590780b16c0 - rayon_core::registry::in_worker::hcb7bd958f38cc0d0
  30:     0x5590780bc2a1 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  31:     0x559077faf819 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hd3d69c760fd2a940
  32:     0x559077426694 - rayon_core::registry::WorkerThread::wait_until_cold::h2a9bfb90a6fe1f2f
  33:     0x5590780b154d - rayon_core::registry::in_worker::hcb7bd958f38cc0d0
  34:     0x5590780bc2a1 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  35:     0x5590780b1492 - rayon_core::registry::in_worker::hcb7bd958f38cc0d0
  36:     0x5590780bc2a1 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  37:     0x5590780b1492 - rayon_core::registry::in_worker::hcb7bd958f38cc0d0
  38:     0x5590780bc2a1 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  39:     0x5590780b1492 - rayon_core::registry::in_worker::hcb7bd958f38cc0d0
  40:     0x5590780bc2a1 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  41:     0x5590780b1492 - rayon_core::registry::in_worker::hcb7bd958f38cc0d0
  42:     0x5590780bc2a1 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7e96df3ca2729ce3
  43:     0x5590780b566e - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd82c551bd02a88fb
  44:     0x559077fae788 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h0804a8744bc570f8
  45:     0x559077426694 - rayon_core::registry::WorkerThread::wait_until_cold::h2a9bfb90a6fe1f2f
  46:     0x55907814108c - rayon_core::registry::ThreadBuilder::run::h987df3e09c9f5d78
  47:     0x55907813f72a - std::sys_common::backtrace::__rust_begin_short_backtrace::h2b435bcf0cdfd916
  48:     0x5590781433e1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h40379d6fc25cd78b
  49:     0x5590784e74e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0e2949e5633573ec
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/alloc/src/boxed.rs:2000:9
  50:     0x5590784e74e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc3e495f171f72161
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/alloc/src/boxed.rs:2000:9
  51:     0x5590784e74e3 - std::sys::unix::thread::Thread::new::thread_start::h995ed3a13a5c937a
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys/unix/thread.rs:108:17
  52:     0x7f2cb74cf609 - start_thread
  53:     0x7f2cb729d133 - clone
  54:                0x0 - <unknown>
root@edereli:~/massa/massa-node#
`

**Comment by ErkanDERELI** [comment]
[massa hata.txt](https://github.com/massalabs/massa/files/10374757/massa.hata.txt)
