### ISSUE TITLE
Crash in a second bootstrap attempt

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3412]
```
2023-01-12T18:36:35.744037Z  INFO massa_node: Node version : TEST.18.0
2023-01-12T18:36:35.858795Z  INFO massa_bootstrap::client: Start bootstrapping from 198.27.74.5:31245
2023-01-12T18:36:36.027402Z  WARN massa_bootstrap::client: Error received from bootstrap server: Bootstrap failed because the bootstrap server currently has no slots available.
2023-01-12T18:36:36.027510Z  INFO massa_bootstrap::client: Bootstrap from server 198.27.74.5:31245 failed. Your node will try to bootstrap from another server in 1s.
2023-01-12T18:36:37.028517Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.120.215:31245
2023-01-12T18:36:37.191766Z  WARN massa_bootstrap::client: Error received from bootstrap server: Bootstrap failed because the bootstrap server currently has no slots available.
2023-01-12T18:36:37.191790Z  INFO massa_bootstrap::client: Bootstrap from server 158.69.120.215:31245 failed. Your node will try to bootstrap from another server in 1s.
2023-01-12T18:36:38.193057Z  INFO massa_bootstrap::client: Start bootstrapping from 92.169.36.208:31245
2023-01-12T18:36:38.205857Z  WARN massa_bootstrap::client: Error while connecting to bootstrap server: io error: Connection refused (os error 111)
2023-01-12T18:36:38.205920Z  INFO massa_bootstrap::client: Bootstrap from server 92.169.36.208:31245 failed. Your node will try to bootstrap from another server in 1s.
2023-01-12T18:36:39.206375Z  INFO massa_bootstrap::client: Start bootstrapping from 54.36.174.177:31245
2023-01-12T18:37:54.072917Z  INFO massa_bootstrap::client: Slot is too old retry bootstrap from scratch
2023-01-12T18:37:54.072929Z  WARN massa_bootstrap::client: Error while bootstrapping: general bootstrap error: Slot too old
2023-01-12T18:37:54.072958Z  INFO massa_bootstrap::client: Bootstrap from server 54.36.174.177:31245 failed. Your node will try to bootstrap from another server in 1s.
2023-01-12T18:37:55.074365Z  INFO massa_bootstrap::client: Start bootstrapping from 51.75.60.228:31245
thread 'main' panicked at 'PoS received cycle (367) should be equal to the next expected cycle (368)', massa-pos-exports/src/pos_final_state.rs:448:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nirnaeth-arnoediad** [comment]
Issue still exist on testnet 19.3. Here more logs:
   ```
Compiling massa_protocol_exports v0.1.0 (/root/massa/massa-protocol-exports)
   Compiling massa_consensus_exports v0.1.0 (/root/massa/massa-consensus-exports)
   Compiling massa_factory_exports v0.1.0 (/root/massa/massa-factory-exports)
   Compiling massa_api_exports v0.1.0 (/root/massa/massa-api-exports)
   Compiling massa_api v0.1.0 (/root/massa/massa-api)
   Compiling massa_factory_worker v0.1.0 (/root/massa/massa-factory-worker)
   Compiling massa_protocol_worker v0.1.0 (/root/massa/massa-protocol-worker)
   Compiling massa_consensus_worker v0.1.0 (/root/massa/massa-consensus-worker)
   Compiling massa_bootstrap v0.1.0 (/root/massa/massa-bootstrap)
   Compiling massa_network_worker v0.1.0 (/root/massa/massa-network-worker)
   Compiling massa_pool_worker v0.1.0 (/root/massa/massa-pool-worker)
   Compiling massa_execution_worker v0.1.0 (/root/massa/massa-execution-worker)
   Compiling massa_pos_worker v0.1.0 (/root/massa/massa-pos-worker)
   Compiling massa_ledger_worker v0.1.0 (/root/massa/massa-ledger-worker)
   Compiling massa-node v0.1.0 (/root/massa/massa-node)
    Finished release [optimized] target(s) in 3m 16s
     Running `/root/massa/target/release/massa-node -p asd123`
2023-02-11T09:47:02.541683Z  INFO massa_node: Node version : TEST.19.3
2023-02-11T09:47:02.587677Z  INFO massa_bootstrap::client: Start bootstrapping from 54.36.174.177:31245
2023-02-11T09:49:44.103636Z  INFO massa_bootstrap::client: Slot is too old retry bootstrap from scratch
2023-02-11T09:49:44.103660Z  WARN massa_bootstrap::client: Error while bootstrapping: general bootstrap error: Slot too old
2023-02-11T09:49:44.104379Z  INFO massa_bootstrap::client: Bootstrap from server 54.36.174.177:31245 failed. Your node will try to bootstrap from another server in 10s.
2023-02-11T09:49:54.105293Z  INFO massa_bootstrap::client: Start bootstrapping from 158.69.120.215:31245
thread 'main' panicked at 'PoS received cycle (33) should be equal to the next expected cycle (37)', massa-pos-exports/src/pos_final_state.rs:448:17
stack backtrace:
   0:     0xaaaab867ae44 - std::backtrace_rs::backtrace::libunwind::trace::h735bdcffea3a3e10
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaab867ae44 - std::backtrace_rs::backtrace::trace_unsynchronized::h7cd4b808057616d7
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaab867ae44 - std::sys_common::backtrace::_print_fmt::h620d00d6994924c1
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:65:5
   3:     0xaaaab867ae44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2775853ceab30152
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaab869a8a4 - core::fmt::write::h4e55d6c1e961a621
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/core/src/fmt/mod.rs:1232:17
   5:     0xaaaab8675c60 - std::io::Write::write_fmt::he44b2d21596f80ff
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/io/mod.rs:1682:15
   6:     0xaaaab867ac50 - std::sys_common::backtrace::_print::hbc0f5a81c454df55
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:47:5
   7:     0xaaaab867ac50 - std::sys_common::backtrace::print::he95bc86c812e0381
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:34:9
   8:     0xaaaab867c664 - std::panicking::default_hook::{{closure}}::h6cb2713d84093e21
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:267:22
   9:     0xaaaab867c3a8 - std::panicking::default_hook::h2a74d7dfff1a7f88
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:286:9
  10:     0xaaaab79591a0 - massa_node::run::{{closure}}::{{closure}}::h21271a9300d1efd6
  11:     0xaaaab867cd0c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbc073cba5771485b
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/alloc/src/boxed.rs:2002:9
  12:     0xaaaab867cd0c - std::panicking::rust_panic_with_hook::h93c7f2b774a6a598
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:692:13
  13:     0xaaaab867cac4 - std::panicking::begin_panic_handler::{{closure}}::hd14aa92e98e7805b
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:579:13
  14:     0xaaaab867b2d4 - std::sys_common::backtrace::__rust_end_short_backtrace::h61c78df49e34ce20
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/sys_common/backtrace.rs:137:18
  15:     0xaaaab867c810 - rust_begin_unwind
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:575:5
  16:     0xaaaab783397c - core::panicking::panic_fmt::hdef73b6ce6bc78af
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/core/src/panicking.rs:64:14
  17:     0xaaaab81ac638 - massa_pos_exports::pos_final_state::PoSFinalState::set_cycle_history_part::h5ae06018ce82c343
  18:     0xaaaab796d81c - massa_bootstrap::client::bootstrap_from_server::{{closure}}::h3125769f5c21fd2e
  19:     0xaaaab7973604 - massa_bootstrap::client::get_state::{{closure}}::he57eac2db6f7e92c
  20:     0xaaaab7994498 - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h2b5cebda071bbfdc
  21:     0xaaaab794e298 - massa_node::launch::{{closure}}::h57b4050d500124bf
  22:     0xaaaab7935674 - tokio::runtime::park::CachedParkThread::block_on::hc4535e14a49bb8ca
  23:     0xaaaab79fa9e0 - tokio::runtime::runtime::Runtime::block_on::h439911235717da34
  24:     0xaaaab787649c - massa_node::main::hd386a27182e20073
  25:     0xaaaab7979604 - std::sys_common::backtrace::__rust_begin_short_backtrace::he6b3192c4d50f94f
  26:     0xaaaab78637f8 - std::rt::lang_start::{{closure}}::h113df9855db75d14
  27:     0xaaaab866f4cc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hda5b56bec5a999f4
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/core/src/ops/function.rs:287:13
  28:     0xaaaab866f4cc - std::panicking::try::do_call::h4dc03db9f4a2d0c3
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:483:40
  29:     0xaaaab866f4cc - std::panicking::try::hdfadce1aa7ef4dcd
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:447:19
  30:     0xaaaab866f4cc - std::panic::catch_unwind::hc0ff535cd1272ede
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panic.rs:140:14
  31:     0xaaaab866f4cc - std::rt::lang_start_internal::{{closure}}::h4f97a5498fe58b0d
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/rt.rs:148:48
  32:     0xaaaab866f4cc - std::panicking::try::do_call::h1eaca6870fb44b42
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:483:40
  33:     0xaaaab866f4cc - std::panicking::try::h7ac7d1e9fced6df3
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panicking.rs:447:19
  34:     0xaaaab866f4cc - std::panic::catch_unwind::h59f62e48fd648011
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/panic.rs:140:14
  35:     0xaaaab866f4cc - std::rt::lang_start_internal::hb6863836d5d1cbcf
                               at /rustc/e972bc8083d5228536dfd42913c8778b6bb04c8e/library/std/src/rt.rs:148:20
  36:     0xaaaab7876650 - main
  37:     0xffffbb667e10 - __libc_start_main
  38:     0xaaaab7853104 - <unknown>
root@my-first ~/m/massa-node (testnet)#
```

**Comment by AurelienFT** [comment]
An other one : ```
[2m2023-02-14T20:26:26.763555Z[0m [33m WARN[0m [2mmassa_bootstrap::client[0m[2m:[0m Error while bootstrapping: general bootstrap error: Parsing Error: Failed BootstrapServerMessage deserialization / Failed final_state_changes deserialization / Count / Failed StateChanges deserialization / Failed async_pool_changes deserialization / Failed AsyncPoolChanges deserialization / Count / Digit / Input: [2, 2, 0, 1, 229, 181, 1, 21, 0, 0, 0, 1, 229, 181, 1, 25, 0, 229, 181, 1, 25, 0, 186, 3, 159, 88, 26, 147, 60, 246, 151, 95, 101, 185, 162, 68, 211, 103, 25, 250, 79, 133, 117, 195, 83, 131, 229, 189, 65, 25, 104, 169, 100, 52, 186, 3, 159, 88, 26, 147, 60, .. 30, 147, 72, 82, 208, 153, 243, 148, 111, 21, 42, 247, 194, 84, 27, 92, 219, 50, 245, 65, 79, 9, 30, 17, 233, 1, 0, 224, 195, 156, 226, 167, 19, 1, 0, 184, 63, 130, 159, 195, 181, 181, 170, 126, 63, 174, 117, 108, 87, 17, 252, 169, 149, 111, 191, 239, 185, 201, 125, 51, 237, 41, 53, 48, 64, 253, 245, 1, 0, 146, 222, 221, 235, 228, 1, 1, 0, 198, 151, 20, 206, 58, 67, 73, 124, 136, 143, 212, 20, 250, 162, 61, 238, 164, 131, 18, 117, 118, 159, 225, 203, 51, 94, 143, 205, 195, 203, 208, 166, 1, 0, 180, 245, 143, 236, 251, 3, 1, 0, 228, 5, 34, 30, 48, 90, 10, 163, 246, 242, 113, 229, 33, 89, 175, 145, 1, 141, 24, 59, 70, 11, 186, 117, 242, 32, 120, 124, 226, 142, 143, 0, 1, 0, 224, 150, 211, 150, 84, 1, 0, 236, 29, 65, 81, 56, 121, 200, 82, 84, 94, 133, 192, 157, 16, 123, 184, 191, 165, 173, 56, 31, 52, 17, 56, 53, 25, 132, 44, 80, 8, 192, 250, 1, 0, 238, 189, 173, 174, 138, 3, 1, 0, 135, 251, 222, 131, 227, 4, 151, 239, 45, 230, 5, 11, 116, 205, 140, 169, 116, 87, 200, 220, 180, 36, 75, 179, 23, 212, 237, 69, 55, 139, 137, 255, 1, 0, 160, 182, 202, 137, 130, 149, 223, 185, 13, 1, 0, 72, 232, 178, 133, 119, 144, 233, 30, 230, 204, 105, 132, 55, 165, 57, 37, 148, 103, 158, 92, 244, 26, 154, 87, 22, 116, 231, 192, 175, 241, 133, 64, 1, 0, 244, 195, 173, 244, 25, 1, 0, 25, 125, 94, 179, 70, 223, 128, 38, 66, 213, 22, 152, 210, 253, 110, 46, 47, 9, 41, 170, 161, 59, 2, 93, 121, 132, 99, 57, 94, 223, 11, 16, 1, 0, 160, 206, 133, 167, 148, 9, 1, 0, 126, 132, 21, 222, 103, 114, 127, 123, 194, 33, 143, 3, 145, 51, 33, 156, 103, 205, 37, 147, 201, 225, 229, 16, 250, 169, 189, 35, 128, 145, 255, 17, 1, 0, 255, 203, 154, 213, 3, 1, 1, 2, 120, 121, 0, 8, 183, 2, 0, 0, 185, 0, 0, 0, 171, 17, 22, 99, 178, 164, 3, 173, 3, 253, 40, 138, 145, 218, 186, 2, 161, 20, 86, 197, 128, 93, 82, 8, 124, 111, 46, 29, 248, 164, 168, 73, 1, 0, 217, 245, 154, 183, 136, 2, 1, 0, 2, 2, 0, 1, 230, 181, 1, 31, 0, 0, 0, 1, 231, 181, 1, 3, 0, 231, 181, 1, 3, 0, 126, 132, 21, 222, 103, 114, 127, 123, 194, 33, 143, 3, 145, 51, 33, 156, 103, 205, 37, 147, 201, 225, 229, 16, 250, 169, 189, 35, 128, 145, 255, 17, 126, 132, 21, 222, 103, 114, 127, 123, 194, 33, 143, 3, 145, 51, 33, 156, 103, 205, 37, 147, 201, 225, 229, 16, 250, 169, 189, 35, 128, 145, 255, 17, 4, 108, 111, 111, 112, 128, 148, 235, 220, 3, 0, 1, 231, 181, 1, 0, 232, 181, 1, 31, 0, 48, 1, 1, 0, 1, 72, 232, 178, 133, 119, 144, 233, 30, 230, 204, 105, 132, 55, 165, 57, 37, 148, 103, 158, 92, 244, 26, 154, 87, 22, 116, 231, 192, 175, 241, 133, 64, 1, 0, 0, 0, 0, 0]
```
