### ISSUE TITLE
failed to build server: Transport(Address already in use (os error 98)

### ISSUE THREAD

**Issue by isezen** [massalabs/massa#3418]
Massa node crashes While trying to bootstrap from a unofficial node. Log output is below.

**Remote node is active and allows all incoming bootstrap requests.**

```
2023-01-13T16:01:17.746558Z  INFO massa_bootstrap::client: Start bootstrapping from 130.61.42.57:31245
2023-01-13T16:01:23.062038Z  INFO massa_bootstrap::client: State bootstrap complete
2023-01-13T16:01:23.225287Z  INFO massa_bootstrap::client: Successful bootstrap
2023-01-13T16:01:23.226036Z  INFO massa_network_worker: The node_id of this node is: N1Ak4Fu6weXJKkG6sW3vgrbCq6dNAJvemh47SJALQwXveQDTJrE
2023-01-13T16:01:23.276771Z  INFO massa_consensus_worker::worker::init: Started node at time 2023-01-13T16:01:23Z, cycle 407, period 52205, thread 5
thread 'main' panicked at 'failed to build server: Transport(Address already in use (os error 98)
Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: <jsonrpsee_core::error::Error as core::convert::From<std::io::error::Error>>::from
   2: jsonrpsee_server::server::Builder<B,L>::build::{{closure}}
   3: massa_api::private::<impl massa_api::RpcServer for massa_api::API<massa_api::Private>>::serve::{{closure}}
   4: massa_node::launch::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::runtime::Runtime::block_on
   7: massa_node::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/core/src/ops/function.rs:606:13
  11: std::panicking::try::do_call
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:483:40
  12: std::panicking::try
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:447:19
  13: std::panic::catch_unwind
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panic.rs:137:14
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/rt.rs:148:48
  15: std::panicking::try::do_call
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:483:40
  16: std::panicking::try
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:447:19
  17: std::panic::catch_unwind
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panic.rs:137:14
  18: std::rt::lang_start_internal
             at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/rt.rs:148:20
  19: main
  20: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  22: _start)', massa-api/src/lib.rs:179:10
stack backtrace:
   0:     0x55e34fa05f4a - std::backtrace_rs::backtrace::libunwind::trace::hfbeb4b2b22d738bc
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e34fa05f4a - std::backtrace_rs::backtrace::trace_unsynchronized::hcb078a4cbf58419c
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e34fa05f4a - std::sys_common::backtrace::_print_fmt::hac5b7a2e71b9d4a2
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55e34fa05f4a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39740540205245e8
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e34fa29efe - core::fmt::write::hbf78108acb1498ba
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/core/src/fmt/mod.rs:1208:17
   5:     0x55e34fa00735 - std::io::Write::write_fmt::h17c5408264a7c236
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/io/mod.rs:1682:15
   6:     0x55e34fa05d15 - std::sys_common::backtrace::_print::h3fcfa786bd91d49d
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55e34fa05d15 - std::sys_common::backtrace::print::h9f68dbc9130a1e43
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55e34fa0784f - std::panicking::default_hook::{{closure}}::h2f0941ce27a29acf
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:267:22
   9:     0x55e34fa0758b - std::panicking::default_hook::h5fc054efab50e987
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:286:9
  10:     0x55e34e9e4c8e - massa_node::run::{{closure}}::{{closure}}::ha056e5e64b418cdd
  11:     0x55e34fa07f7d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha98456fc8f91c853
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/alloc/src/boxed.rs:2032:9
  12:     0x55e34fa07f7d - std::panicking::rust_panic_with_hook::h21670202cf8178d4
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:692:13
  13:     0x55e34fa07cf9 - std::panicking::begin_panic_handler::{{closure}}::h92d41791709d0592
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:579:13
  14:     0x55e34fa063fc - std::sys_common::backtrace::__rust_end_short_backtrace::hadd55dccca5a9b00
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x55e34fa07a02 - rust_begin_unwind
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:575:5
  16:     0x55e34e972fb3 - core::panicking::panic_fmt::h5499993c5ba4eb21
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/core/src/panicking.rs:64:14
  17:     0x55e34e973443 - core::result::unwrap_failed::ha3d340cfbae779d8
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/core/src/result.rs:1790:5
  18:     0x55e34f26e68c - massa_api::private::<impl massa_api::RpcServer for massa_api::API<massa_api::Private>>::serve::{{closure}}::hdc8f7cfecc89eb7a
  19:     0x55e34e9de139 - massa_node::launch::{{closure}}::h37f6532f75d8a791
  20:     0x55e34e9cff54 - tokio::runtime::park::CachedParkThread::block_on::hffce8d9af7e5e9d5
  21:     0x55e34eae0870 - tokio::runtime::runtime::Runtime::block_on::hc08e5d2638413eb1
  22:     0x55e34eb10400 - massa_node::main::h5c0a6d4f26915edf
  23:     0x55e34ea8cf53 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9b1c1214dd380457
  24:     0x55e34ead5fdd - std::rt::lang_start::{{closure}}::h25bbe9bd2b12c5bf
  25:     0x55e34f9f9f9c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha21c39ffd5fcb6b0
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/core/src/ops/function.rs:606:13
  26:     0x55e34f9f9f9c - std::panicking::try::do_call::hfcb5b7de6a967aa4
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:483:40
  27:     0x55e34f9f9f9c - std::panicking::try::h852b554f2a216a1e
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:447:19
  28:     0x55e34f9f9f9c - std::panic::catch_unwind::h138950e22f10d85b
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panic.rs:137:14
  29:     0x55e34f9f9f9c - std::rt::lang_start_internal::{{closure}}::h0de24c6b40b0e960
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/rt.rs:148:48
  30:     0x55e34f9f9f9c - std::panicking::try::do_call::hd6b16c5e5da3ce3b
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:483:40
  31:     0x55e34f9f9f9c - std::panicking::try::hb7de684c95f0cf1d
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panicking.rs:447:19
  32:     0x55e34f9f9f9c - std::panic::catch_unwind::h8cc7b91a0a2687e5
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/panic.rs:137:14
  33:     0x55e34f9f9f9c - std::rt::lang_start_internal::hf69e88a76ee34b77
                               at /rustc/af3e06f1bf4ca49407562b1b84744e27905bea98/library/std/src/rt.rs:148:20
  34:     0x55e34eb10575 - main
  35:     0x7faefbe74d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x7faefbe74e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  37:     0x55e34e99a19a - _start
  38:                0x0 - <unknown>
```

**Comment by AurelienFT** [comment]
Hello,

Thanks for the report.
It seems that the address/port you configured for the private PAI is already used in your machine

**Comment by aoudiamoncef** [comment]
Hi, 

Run the command below to see which process is taking your ports:
```shell
sudo lsof -i -P -n | grep LISTEN
```

Then kill the process:
```shell
pkill PROCESS_NAME
```

**Comment by AurelienFT** [comment]
Hello,

Without more details it's complicated to address your problem. Thanks for the reporting, i'm closing this if you have any new informations you can re-open :)
