### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by Mikis92** [massalabs/massa#3727]
Bonjour,

Mon node vient de crash.
OK après relance.

Voici le log

2023-03-25T09:51:16.500760Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 15999, thread: 1): `CycleUnavailable`: PoS cycle 124 is needed but is absent from cache
2023-03-25T09:51:16.500760Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 15998, thread: 17): `CycleUnavailable`: PoS cycle 124 is needed but is absent from cache
thread 'execution' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(124)', massa-execution-worker/src/execution.rs:974:18
stack backtrace:
   0:     0x557ed0e677fa - std::backtrace_rs::backtrace::libunwind::trace::h04a9b397a1c0c60d
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557ed0e677fa - std::backtrace_rs::backtrace::trace_unsynchronized::h5e9b19d732b9188e
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557ed0e677fa - std::sys_common::backtrace::_print_fmt::hb53d30166cffe1c4
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x557ed0e677fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb60f56a68fee7715
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557ed0e8b3ae - core::fmt::write::h7286a9b7c98a1aec
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/core/src/fmt/mod.rs:1232:17
   5:     0x557ed0e61f65 - std::io::Write::write_fmt::hb0964461831cd037
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/io/mod.rs:1684:15
   6:     0x557ed0e675c5 - std::sys_common::backtrace::_print::hcbd27bb43c0b7aa3
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x557ed0e675c5 - std::sys_common::backtrace::print::h60def56b73c38f45
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557ed0e690cf - std::panicking::default_hook::{{closure}}::ha4b6fe1d592fd438
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:271:22
   9:     0x557ed0e68e0b - std::panicking::default_hook::hbca0fde97bcb45ab
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:290:9
  10:     0x557ecfe8e96e - massa_node::run::{{closure}}::{{closure}}::h25b7e97217ac0e39
  11:     0x557ed0e697fd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc2bce42932818f42
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/alloc/src/boxed.rs:2002:9
  12:     0x557ed0e697fd - std::panicking::rust_panic_with_hook::h986441b536730980
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:696:13
  13:     0x557ed0e69579 - std::panicking::begin_panic_handler::{{closure}}::h562ebdec65f50fd8
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:583:13
  14:     0x557ed0e67c66 - std::sys_common::backtrace::__rust_end_short_backtrace::h2159507abad28e50
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x557ed0e69282 - rust_begin_unwind
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:579:5
  16:     0x557ecfd63023 - core::panicking::panic_fmt::hb3aae2e027d92e48
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/core/src/panicking.rs:64:14
  17:     0x557ecfd634d3 - core::result::unwrap_failed::h6c92b295e6e1e66e
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/core/src/result.rs:1750:5
  18:     0x557ed058b6c2 - massa_execution_worker::execution::ExecutionState::execute_slot::hf99c30afec8dc461
  19:     0x557ed058cf03 - massa_execution_worker::execution::ExecutionState::execute_candidate_slot::h309df9af269560b5
  20:     0x557ed05abc2f - massa_execution_worker::worker::ExecutionThread::main_loop::{{closure}}::h29e7bf490dde2742
  21:     0x557ed05ab818 - massa_execution_worker::slot_sequencer::SlotSequencer::run_task_with::h1fbe3063db57cb4a
  22:     0x557ed057edfe - massa_execution_worker::worker::ExecutionThread::main_loop::hc734ba14523f120c
  23:     0x557ed05dcef4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h91c1a5364d5ba6e1
  24:     0x557ed05a3de7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h03e578866a91ca84
  25:     0x557ed0e6c5e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb3f6faca7c156171
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/alloc/src/boxed.rs:1988:9
  26:     0x557ed0e6c5e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h02880bc4bfdd3a86
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/alloc/src/boxed.rs:1988:9
  27:     0x557ed0e6c5e3 - std::sys::unix::thread::Thread::new::thread_start::hd7dc35cd4b3b6473
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f5ab6c94b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  29:     0x7f5ab6d26a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  30:                0x0 - <unknown>

**Comment by vkomenda** [comment]
I had a similar crash as well. I fixed it with a restart. I believe the node can do a soft recovery instead of crashing.

```
023-04-24T03:13:18.561621Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.                                      
2023-04-24T03:13:18.561742Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2023-04-24T03:13:18.562905Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2023-04-24T03:13:18.564128Z  INFO massa_network_worker::network_event::event_impl: Send network event failed An error occurred during channel communication: Failed to send event.
2023-04-24T03:13:18.741653Z  WARN massa_factory_worker::denunciation_factory: Cannot get producer from selector: `CycleUnavailable`: PoS cycle 372 is needed but is absent from cache
2023-04-24T03:13:18.959887Z  WARN massa_protocol_worker::protocol_network: Node N12Ko5NRA2jmqvmbBjNt1D34FrUUc5RmUK7Lg6EcbxdMKfmAUovM sent us an operation list but we don't have block id B12BxeNsdrEpZdK9VsXbDxwzJHy9Qm8gRj1E7efjaUKRJyzVcSar in our wishlist.
2023-04-24T03:13:18.959973Z  WARN massa_protocol_worker::protocol_network: Node N12Ko5NRA2jmqvmbBjNt1D34FrUUc5RmUK7Lg6EcbxdMKfmAUovM sent us an operation list but we don't have block id B12fqP94zL4FpooLgGrcgr5EAupDGuxFaJuxeViz4FaAe4DmUkYn in our wishlist.                                                                                                                                                                                 2023-04-24T03:13:18.959994Z  WARN massa_protocol_worker::protocol_network: Node N12Ko5NRA2jmqvmbBjNt1D34FrUUc5RmUK7Lg6EcbxdMKfmAUovM sent us an operation list but we don't have block id B12uwmQ8ySm7SXep5yktGiarG28Utzz3Udxt3KFjFNeWWySsqGwA in our wishlist.                                                                                                                                                                                 2023-04-24T03:13:18.960015Z  WARN massa_protocol_worker::protocol_network: Node N12Ko5NRA2jmqvmbBjNt1D34FrUUc5RmUK7Lg6EcbxdMKfmAUovM sent us an operation list but we don't have block id B12Jqc3hx1RXVvgX1W2R1BtWmkrYfRGikB5pbtPcZngyXjTNGQk in our wishlist.                                                                                                                                                                                  2023-04-24T03:13:19.001068Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 89600, thread: 14): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                        
2023-04-24T03:13:19.395042Z  WARN massa_factory_worker::denunciation_factory: Cannot get producer from selector: `CycleUnavailable`: PoS cycle 372 is needed but is absent from cache
2023-04-24T03:13:19.500700Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 89600, thread: 15): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                        2023-04-24T03:13:20.000834Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 89600, thread: 16): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                        2023-04-24T03:13:20.000834Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 89600, thread: 0): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                                     2023-04-24T03:13:20.048859Z  WARN massa_factory_worker::denunciation_factory: Cannot get producer from selector: `CycleUnavailable`: PoS cycle 372 is needed but is absent from cache
2023-04-24T03:13:20.222282Z  INFO massa_consensus_worker::worker::main_loop: Started cycle 700                                                                                                                          
2023-04-24T03:13:20.268662Z  WARN massa_factory_worker::denunciation_factory: Cannot get producer from selector: `CycleUnavailable`: PoS cycle 372 is needed but is absent from cache
2023-04-24T03:13:20.482049Z  WARN massa_factory_worker::denunciation_factory: Cannot get producer from selector: `CycleUnavailable`: PoS cycle 372 is needed but is absent from cache
2023-04-24T03:13:20.500965Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 89600, thread: 17): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                        2023-04-24T03:13:20.500991Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 89600, thread: 1): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                                     
2023-04-24T03:13:20.915213Z  WARN massa_factory_worker::denunciation_factory: Cannot get producer from selector: `CycleUnavailable`: PoS cycle 372 is needed but is absent from cache
2023-04-24T03:13:21.000143Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 89600, thread: 2): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                                     2023-04-24T03:13:21.001092Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 89600, thread: 18): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                        2023-04-24T03:13:21.346875Z  WARN massa_factory_worker::denunciation_factory: Cannot get producer from selector: `CycleUnavailable`: PoS cycle 372 is needed but is absent from cache
2023-04-24T03:13:21.500265Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 89600, thread: 19): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                        2023-04-24T03:13:21.500593Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 89600, thread: 3): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                                     2023-04-24T03:13:21.997710Z  WARN massa_protocol_worker::protocol_network: Node N12Ko5NRA2jmqvmbBjNt1D34FrUUc5RmUK7Lg6EcbxdMKfmAUovM sent us an operation list but we don't have block id B1MQB2F7u5AJEQtfPTaaLisnUXihQWDdWD2MKJhy2PmT9W7syv2 in our wishlist.                                                                                                                                                                                  2023-04-24T03:13:21.997765Z  WARN massa_protocol_worker::protocol_network: Node N12Ko5NRA2jmqvmbBjNt1D34FrUUc5RmUK7Lg6EcbxdMKfmAUovM sent us an operation list but we don't have block id B12UbL2MnMNaFsbZpERupyX4xgM1skRDhtzQTNqsffwYbwPtk2jE in our wishlist.                                                                                                                                                                                 2023-04-24T03:13:22.000591Z  WARN massa_factory_worker::endorsement_factory: endorsement factory could not get selector draws for slot (period: 89600, thread: 20): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                        2023-04-24T03:13:22.000719Z  WARN massa_factory_worker::block_factory: block factory could not get selector draws for slot (period: 89600, thread: 4): `CycleUnavailable`: PoS cycle 700 is needed but is absent from cache                                                                                                                                                                                                                     thread 'execution' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(700)', massa-execution-worker/src/execution.rs:997:18                   
```

**Comment by AurelienFT** [comment]
This crash doesn't seems to appear anymore since two months. Closing it.
