### ISSUE TITLE
Node with the latest source code doesn't run

### ISSUE THREAD

**Issue by michaelfastov** [massalabs/massa#3749]
I followed the guide to run the node: https://docs.massa.net/en/latest/testnet/running.html
I pulled the latest version of a node, run the command to launch the node and got the error that asks to update the node.
I installed all dependencies.

I used this commands to update the node (as in guide):
```
cd massa/
git stash
git remote set-url origin https://github.com/massalabs/massa.git
git checkout testnet
git pull
```
```

root@vmi1258942:~/massa# git checkout testnet
Already on 'testnet'
Your branch is up to date with 'origin/testnet'.
root@vmi1258942:~/massa# git pull
Already up to date.
root@vmi1258942:~/massa#
```

**To Reproduce**
follow the guide
https://docs.massa.net/en/latest/testnet/install.html

**Expected behavior**
Node runs successfully

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

Error:
```
root@vmi1258942:~/massa/massa-node# RUST_BACKTRACE=full cargo run --release -- -p MY_PASS|& tee logs.txt
warning: /root/massa/massa-node/Cargo.toml: unused manifest key: build
    Finished release [optimized] target(s) in 1.03s
     Running `/root/massa/target/release/massa-node -p MY_PASS`
2023-04-02T18:05:28.454277Z  INFO massa_node: Node version : TEST.20.2
thread 'main' panicked at 'This episode has come to an end, please get the latest testnet node version to continue', massa-node/src/main.rs:99:13
stack backtrace:
   0:     0x55576e5c87fa - std::backtrace_rs::backtrace::libunwind::trace::h04a9b397a1c0c60d
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55576e5c87fa - std::backtrace_rs::backtrace::trace_unsynchronized::h5e9b19d732b9188e
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55576e5c87fa - std::sys_common::backtrace::_print_fmt::hb53d30166cffe1c4
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55576e5c87fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb60f56a68fee7715
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55576e5ec3ae - core::fmt::write::h7286a9b7c98a1aec
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/core/src/fmt/mod.rs:1232:17
   5:     0x55576e5c2f65 - std::io::Write::write_fmt::hb0964461831cd037
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/io/mod.rs:1684:15
   6:     0x55576e5c85c5 - std::sys_common::backtrace::_print::hcbd27bb43c0b7aa3
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55576e5c85c5 - std::sys_common::backtrace::print::h60def56b73c38f45
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55576e5ca0cf - std::panicking::default_hook::{{closure}}::ha4b6fe1d592fd438
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:271:22
   9:     0x55576e5c9e0b - std::panicking::default_hook::hbca0fde97bcb45ab
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:290:9
  10:     0x55576d60080e - massa_node::run::{{closure}}::{{closure}}::h25b7e97217ac0e39
  11:     0x55576e5ca7fd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc2bce42932818f42
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/alloc/src/boxed.rs:2002:9
  12:     0x55576e5ca7fd - std::panicking::rust_panic_with_hook::h986441b536730980
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:696:13
  13:     0x55576e5ca532 - std::panicking::begin_panic_handler::{{closure}}::h562ebdec65f50fd8
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:581:13
  14:     0x55576e5c8c66 - std::sys_common::backtrace::__rust_end_short_backtrace::h2159507abad28e50
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x55576e5ca282 - rust_begin_unwind
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:579:5
  16:     0x55576d4dc4a3 - core::panicking::panic_fmt::hb3aae2e027d92e48
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/core/src/panicking.rs:64:14
  17:     0x55576d5fad1b - massa_node::launch::{{closure}}::h2ff93f2ce849ccf5
  18:     0x55576d5eb9f8 - tokio::runtime::park::CachedParkThread::block_on::h4b088d18dea39e77
  19:     0x55576d626ee9 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h4985a04fc2793a39
  20:     0x55576d572750 - tokio::runtime::runtime::Runtime::block_on::h623a7f3bda276b98
  21:     0x55576d62c2b2 - massa_node::main::hf662314d486b374d
  22:     0x55576d58e9f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc53d7aaa944c2b60
  23:     0x55576d5c116d - std::rt::lang_start::{{closure}}::h42c15b83b5adde3b
  24:     0x55576e5bc42c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::haf51fd52d8c9cfd0
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/core/src/ops/function.rs:287:13
  25:     0x55576e5bc42c - std::panicking::try::do_call::h14c594ff21e388e0
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:487:40
  26:     0x55576e5bc42c - std::panicking::try::h3051cd27c42057e5
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:451:19
  27:     0x55576e5bc42c - std::panic::catch_unwind::h92fc2917a79750c2
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panic.rs:140:14
  28:     0x55576e5bc42c - std::rt::lang_start_internal::{{closure}}::h272f0038f3d1ae58
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/rt.rs:148:48
  29:     0x55576e5bc42c - std::panicking::try::do_call::h18863c27bb56ce00
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:487:40
  30:     0x55576e5bc42c - std::panicking::try::h3a51cfc6ee986882
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panicking.rs:451:19
  31:     0x55576e5bc42c - std::panic::catch_unwind::h7fccea8fb46000e8
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/panic.rs:140:14
  32:     0x55576e5bc42c - std::rt::lang_start_internal::hda84c4118af2e1ef
                               at /rustc/d962ea57899d64dc8a57040142c6b498a57c8064/library/std/src/rt.rs:148:20
  33:     0x55576d62c465 - main
  34:     0x7fd703958083 - __libc_start_main
  35:     0x55576d5007fe - _start
  36:                0x0 - <unknown>

```

**Comment by Ben-PH** [comment]
Testnet 20 has come to its scheduled end. I think testnet 21 will be launched by the 10th.

You can join the conversation in the testnet channel in the massa community discord server: https://discord.com/invite/massa
