### ISSUE TITLE
Node crash report

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3916]
Node started at 2m2023-05-05 17:44:42 and crashed 2023-05-05 22:07:36

Logs
```shell
[2m2023-05-05T22:06:09.997542Z[0m [34mDEBUG[0m [2mmassa_pool_worker::denunciation_pool[0m[2m:[0m Cannot get producer from selector: `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:09.997611Z[0m [34mDEBUG[0m 
[2mmassa_pool_worker::denunciation_pool[0m[2m:[0m Cannot get producer from selector: `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:09.997630Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::propagation[0m[2m:[0m Send endorsements of len 2 to P12BZBHfVwpXEvFxczETMdq3iFhorCoNdxhDGMU7AZURsZkhHajT
[2m2023-05-05T22:06:09.998019Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::block_handler::retrieval[0m[2m:[0m Received block message: BlockHeader from P12vxrYTQzS5TRzxLfFNYxn6PyEsphKWkdqx2mVfEuvJ9sPF43uq
[2m2023-05-05T22:06:09.998034Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::propagation[0m[2m:[0m Send endorsements of len 1 to P12kXCmzuRBq1wkJN6CEuS1st8nEWAnkoLto6reHrHTYmpcezxHc
[2m2023-05-05T22:06:09.998067Z[0m [34mDEBUG[0m [2mmassa_pool_worker::denunciation_pool[0m[2m:[0m Cannot get producer from selector: `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:09.998047Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::retrieval[0m[2m:[0m Received endorsement message: Endorsement from P12vxrYTQzS5TRzxLfFNYxn6PyEsphKWkdqx2mVfEuvJ9sPF43uq
[2m2023-05-05T22:06:09.998108Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::propagation[0m[2m:[0m Send endorsements of len 1 to P12BZBHfVwpXEvFxczETMdq3iFhorCoNdxhDGMU7AZURsZkhHajT
[2m2023-05-05T22:06:09.998534Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::propagation[0m[2m:[0m Send endorsements of len 1 to P12kXCmzuRBq1wkJN6CEuS1st8nEWAnkoLto6reHrHTYmpcezxHc
[2m2023-05-05T22:06:09.998576Z[0m [34mDEBUG[0m [2mmassa_pool_worker::denunciation_pool[0m[2m:[0m Cannot get producer from selector: `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:09.998587Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::propagation[0m[2m:[0m Send endorsements of len 1 to P12BZBHfVwpXEvFxczETMdq3iFhorCoNdxhDGMU7AZURsZkhHajT
[2m2023-05-05T22:06:09.998732Z[0m [34mDEBUG[0m [2mmassa_pool_worker::denunciation_pool[0m[2m:[0m Cannot get producer from selector: `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:09.998745Z[0m [34mDEBUG[0m [2mmassa_consensus_worker::state::process_commands[0m[2m:[0m received header B12aVAx7FEpkvJaR85LW5yfbpRUMD5Dyr2qH5eEVHpj1xpFeBgcF for slot (period: 2048, thread: 3)
[2m2023-05-05T22:06:10.000159Z[0m [33m WARN[0m [2mmassa_factory_worker::endorsement_factory[0m[2m:[0m endorsement factory could not get selector draws for slot (period: 2048, thread: 20): `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:10.000345Z[0m [33m WARN[0m [2mmassa_factory_worker::block_factory[0m[2m:[0m block factory could not get selector draws for slot (period: 2048, thread: 4): `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:10.000991Z[0m [34mDEBUG[0m [2mmassa_execution_worker::worker[0m[2m:[0m Execution loop triggered, input_data = stop=false, finalized={}, blockclique=None, readonly=RequestQueue { max_items: 10000, queue: [] }
[2m2023-05-05T22:06:10.002157Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::block_handler::retrieval[0m[2m:[0m Received block message: BlockHeader from P12vxrYTQzS5TRzxLfFNYxn6PyEsphKWkdqx2mVfEuvJ9sPF43uq
[2m2023-05-05T22:06:10.002417Z[0m [34mDEBUG[0m [2mmassa_execution_worker::execution[0m[2m:[0m execute_candidate_slot: executing slot=(period: 2048, thread: 0) target=None
[2m2023-05-05T22:06:10.002584Z[0m [34mDEBUG[0m [2mmassa_pool_worker::denunciation_pool[0m[2m:[0m Cannot get producer from selector: `CycleUnavailable`: PoS cycle 16 is needed but is absent from cache
[2m2023-05-05T22:06:10.002632Z[0m [34mDEBUG[0m [2mmassa_execution_worker::execution[0m[2m:[0m executing 0 messages at slot (period: 2048, thread: 0)
thread 'execution' panicked at 'couldn't get the expected block producer for a missed slot: CycleUnavailable(16)', massa-execution-worker/src/execution.rs:1164:18
stack backtrace:
[2m2023-05-05T22:06:10.003661Z[0m [34mDEBUG[0m [2mmassa_consensus_worker::state::process_commands[0m[2m:[0m received header B12UHs7DdwjSu2EU4fd6WRyfhWmyQB1fsvu8a5Pmd1GiksD98oFi for slot (period: 2048, thread: 4)
[2m2023-05-05T22:06:10.004688Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::block_handler::retrieval[0m[2m:[0m Received block message: BlockHeader from P12BZBHfVwpXEvFxczETMdq3iFhorCoNdxhDGMU7AZURsZkhHajT
   0:     0x562cfb9b95d1 - std::backtrace_rs::backtrace::libunwind::trace::hc9361e36aeb59839
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562cfb9b95d1 - std::backtrace_rs::backtrace::trace_unsynchronized::h9236c8bfdcb4bd80
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x[2m2023-05-05T22:06:10.014947Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::retrieval[0m[2m:[0m Received endorsement message: Endorsement from P12BZBHfVwpXEvFxczETMdq3iFhorCoNdxhDGMU7AZURsZkhHajT
562cfb9b95d1 - std::sys_common::backtrace::_print_fmt::h7fcfbb49f6ba2502
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/sys_common/backtrace.rs:65:5
   3[2m2023-05-05T22:06:10.014991Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::retrieval[0m[2m:[0m Received endorsement message: Endorsement from P12BZBHfVwpXEvFxczETMdq3iFhorCoNdxhDGMU7AZURsZkhHajT
:     0x562cfb9b95d1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::[2m2023-05-05T22:06:10.015014Z[0m [34mDEBUG[0m [2mmassa_protocol_worker::handlers::endorsement_handler::retrieval[0m[2m:[0m Received endorsement message: Endorsement from P12BZBHfVwpXEvFxczETMdq3iFhorCoNdxhDGMU7AZURsZkhHajT
fmt::h79701e9b22410d70
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562cfb9e253f - core::fmt::rt::Argument::fmt::hd0e21085a8ceb988
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/core/src/fmt/rt.rs:138:9
   5:     0x562cfb9e253f - core::fmt::write::h4fc8327a2048dd4d
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/core/src/fmt/mod.rs:1094:21
   6:     0x562cfb9b5951 - std::io::Write::write_fmt::hc0f49c54197144fb
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/io/mod.rs:1712:15
   7:     0x562cfb9b93e5 - std::sys_common::backtrace::_print::h9e223a02ac862cb5
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x562cfb9b93e5 - std::sys_common::backtrace::print::h8094443d63ecfb4c
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x562cfb9babf7 - std::panicking::default_hook::{{closure}}::hbf12cbeeb299f3f1
  10:     0x562cfb9ba9e4 - std::panicking::default_hook::h79422e3bc5c0d82d
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/panicking.rs:288:9
  11:     0x562cfa4b507e - massa_node::run::{{closure}}::{{closure}}::h4b6fccca17f2a6d1
  12:     0x562cfb9bb207 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfeb88eb8dfd6ec3a
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/alloc/src/boxed.rs:1999:9
  13:     0x562cfb9bb207 - std::panicking::rust_panic_with_hook::hecec3b7c59290886
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/panicking.rs:695:13
  14:     0x562cfb9baf87 - std::panicking::begin_panic_handler::{{closure}}::h87e403c8e6c6e41e
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/panicking.rs:582:13
  15:     0x562cfb9b9a16 - std::sys_common::backtrace::__rust_end_short_backtrace::hbdd5d6ae6c35db8a
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/sys_common/backtrace.rs:150:18
  16:     0x562cfb9bacf2 - rust_begin_unwind
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/panicking.rs:578:5
  17:     0x562cfa2d1513 - core::panicking::panic_fmt::h0fbc2a051543a5d5
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/core/src/panicking.rs:67:14
  18:     0x562cfa2d19b3 - core::result::unwrap_failed::h4d0dc555e0517944
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/core/src/result.rs:1651:5
  19:     0x562cfa7a1605 - massa_execution_worker::execution::ExecutionState::execute_slot::h0f074f90497030a6
  20:     0x562cfa7a2f80 - massa_execution_worker::execution::ExecutionState::execute_candidate_slot::h565b77d0253d0290
  21:     0x562cfa7ba231 - massa_execution_worker::worker::ExecutionThread::main_loop::{{closure}}::h38f4a8f89bc2df70
  22:     0x562cfa7b8975 - massa_execution_worker::slot_sequencer::SlotSequencer::run_task_with::h9e2f854d853aacf9
  23:     0x562cfa787419 - massa_execution_worker::worker::ExecutionThread::main_loop::h71e2865eea7b7658
  24:     0x562cfa7b2b2e - std::sys_common::backtrace::__rust_begin_short_backtrace::h1daec408b23dfee5
  25:     0x562cfa7b3682 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hae39cc0132dbde0b
  26:     0x562cfb9be2e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hed918a1540dc7a50
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/alloc/src/boxed.rs:1985:9
  27:     0x562cfb9be2e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h606682b9bd0e55ac
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/alloc/src/boxed.rs:1985:9
  28:     0x562cfb9be2e5 - std::sys::unix::thread::Thread::new::thread_start::h0bbd7726c94faa71
                               at /rustc/9ecda8de85ce893cc3fc748ab06be0b8250147a7/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7f621e198ea7 - start_thread
  30:     0x7f621df6ca2f - clone
  31:                0x0 - <unknown>
  ```

![image](https://user-images.githubusercontent.com/22281426/236610828-1793189d-486f-463b-9d04-1c997a313959.png)

[logs_last_1424_lines.txt](https://github.com/massalabs/massa/files/11411818/logs_last_1424_lines.txt)

**Comment by AurelienFT** [comment]
It's probably because you were not connected to any peers because of some bugs in network refactoring will be surely fix by : https://github.com/massalabs/massa/pull/3915
