### ISSUE TITLE
massa metrics listener causes panic on resync.

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#4148]
Caught while testing #4147 in labnet. Panic cleared out once when I deactivated the massa-metric system.

To recreate the panic: (#4150 adds this behind a feature-gate)

before the launch loop: 

```rust
    let start = Instant::now();
    let mut resynced = false;
```

...and in the launch loop

```rust
            if !resynced && start.elapsed() > Duration::from_secs(10) {
                resynced = true;
                warn!("in response to a desynchronization, the node is going to bootstrap again");
                break true;
            }
        };
        stop(
            consensus_event_receiver,
            Managers {

```

log:

```
2023-06-23T16:39:35.477808Z  INFO massa_protocol_worker::connectivity: Trying to connect to addr 51.75.131.129:31244
2023-06-23T16:39:35.655763Z  INFO massa_protocol_worker::handlers::peer_handler: Peer connected: PeerId { public_key: P12sNdL7YwSawpnJrk9XCWDjKbgfNamAobp62AX5qfkgpBkGh2wC }
2023-06-23T16:39:39.191882Z  WARN massa_node: in response to a desynchronization, the node is going to bootstrap again
2023-06-23T16:39:39.191989Z  INFO massa_bootstrap::server: ip white/blacklist updater exited cleanly
2023-06-23T16:39:39.192101Z  INFO massa_node: Start stopping API's: gRPC, EXPERIMENTAL, PUBLIC, PRIVATE
2023-06-23T16:39:39.192155Z  INFO massa_grpc::server: gRPC API stop signal sent successfully
2023-06-23T16:39:39.192174Z  INFO massa_api: API stop signal sent successfully
2023-06-23T16:39:39.192246Z  INFO massa_node: API | EXPERIMENTAL JsonRPC | stopped
2023-06-23T16:39:39.192261Z  INFO massa_api: API stop signal sent successfully
2023-06-23T16:39:39.192358Z  INFO massa_node: API | PUBLIC JsonRPC | stopped
2023-06-23T16:39:39.192372Z  INFO massa_api: API stop signal sent successfully
2023-06-23T16:39:39.192441Z  INFO massa_node: API | PRIVATE JsonRPC | stopped
2023-06-23T16:39:39.192455Z  INFO massa_factory_worker::manager: stopping factory...
2023-06-23T16:39:39.192731Z  INFO massa_factory_worker::manager: factory stopped
2023-06-23T16:39:39.192747Z  INFO massa_protocol_worker::manager: stopping protocol module...
Stopping protocol
Removing connection from: PeerId { public_key: P12sNdL7YwSawpnJrk9XCWDjKbgfNamAobp62AX5qfkgpBkGh2wC }
Stoppeed network controller
2023-06-23T16:39:39.193065Z  INFO massa_protocol_worker::handlers::operation_handler::retrieval: Stop operation retrieval thread
2023-06-23T16:39:39.193196Z  INFO massa_protocol_worker::handlers::operation_handler::propagation: Stop operation propagation thread
Stopped operation handler
2023-06-23T16:39:39.193290Z  INFO massa_protocol_worker::handlers::endorsement_handler::retrieval: Stop endorsement retrieval thread
2023-06-23T16:39:39.193453Z  INFO massa_protocol_worker::handlers::endorsement_handler::propagation: Stop endorsement propagation thread
Stopped endorsement handler
2023-06-23T16:39:39.193559Z  INFO massa_protocol_worker::handlers::block_handler::retrieval: Stop block retrieval thread from command receiver
2023-06-23T16:39:39.193836Z  INFO massa_protocol_worker::handlers::block_handler::propagation: Stop block propagation thread
Stopped block handler
Stopped peer handler
2023-06-23T16:39:39.196187Z  INFO massa_consensus_worker::manager: stopping consensus worker...
2023-06-23T16:39:40.667372Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: integrated_block command send error
2023-06-23T16:39:40.681171Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error
2023-06-23T16:39:40.707481Z  INFO massa_consensus_worker::manager: consensus worker stopped
2023-06-23T16:39:40.707502Z  INFO massa_pool_worker::controller_impl: stopping pool workers...
2023-06-23T16:39:40.709009Z  INFO massa_pool_worker::controller_impl: pool workers stopped
2023-06-23T16:39:40.709022Z  INFO massa_execution_worker::controller: stopping Execution controller...
2023-06-23T16:39:40.728319Z  INFO massa_execution_worker::controller: execution controller stopped
2023-06-23T16:39:40.728332Z  INFO massa_pos_worker::controller: stopping selector worker...
2023-06-23T16:39:40.730572Z  INFO massa_pos_worker::controller: selector worker stopped
2023-06-23T16:39:40.730627Z  INFO massa_node: Node version : LABN.7.7
thread '<unnamed>' panicked at 'error binding to 0.0.0.0:9898: error creating server listener: Address already in use (os error 98)', /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/server/server.rs:79:13
stack backtrace:
2023-06-23T16:39:40.747743Z  INFO massa_final_state::final_state: final_state hash at slot (period: 0, thread: 31): 11111111111111111111111111111111273Yts
2023-06-23T16:39:40.747796Z  INFO massa_bootstrap::client: Start bootstrapping from 51.75.131.129:31245
   0: rust_begin_unwind
             at /rustc/871b5952023139738f72eba235063575062bc2e9/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/871b5952023139738f72eba235063575062bc2e9/library/core/src/panicking.rs:67:14
   2: hyper::server::server::Server<hyper::server::tcp::AddrIncoming,()>::bind::{{closure}}
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/server/server.rs:79:13
   3: core::result::Result<T,E>::unwrap_or_else
             at /rustc/871b5952023139738f72eba235063575062bc2e9/library/core/src/result.rs:1428:23
   4: hyper::server::server::Server<hyper::server::tcp::AddrIncoming,()>::bind
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/server/server.rs:78:48
   5: massa_metrics::server::bind_metrics::{{closure}}::{{closure}}
             at /path/to/rust/massa/massa-metrics/src/server.rs:16:26
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:63
   7: tokio::runtime::coop::with_budget
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:31
  10: tokio::runtime::context::BlockingRegionGuard::block_on
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:315:13
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  12: tokio::runtime::runtime::Runtime::block_on
             at /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  13: massa_metrics::server::bind_metrics::{{closure}}
             at /path/to/rust/massa/massa-metrics/src/server.rs:15:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by damip** [comment]
This problem was observed and confirmed by the Inno team as well. It forces them to wait 30sec after killing the node to be able to launch it again (otherwise it crashes with addr_already_in_use)

**Comment by modship** [comment]
I need to add a stop for the metrics server

**Comment by AurelienFT** [comment]
Can we close this @modship  ? and link the PR that fix.
